# Richieste AJAX {#ajax}
JavaScript ti permette di definire dinamicamente il contenuto di una web page, generando il DOM a runtime invece che nei file `.html` source. Uno dei motivi principali per cui vogliamo produrre dinamicamente un DOM e' quando il contenuto della web page si basa su **data** che possono cambiare nel tempo: per esempio, il tipo di data disponibile tramite una [**Web API**](https://info201.github.io/apis.html#what-is-a-web-api). Usando JavaScript per renderizzare il DOM, puoi produrre rapidamente grandi quantita' di HTML necessarie per mostrare grandi data set, assicurandoti di avere data aggiornati ogni volta che la pagina si carica, e perfino _aggiornare automaticamente il contenuto della pagina_ senza richiedere all'utente di ricaricare!

Questo capitolo descrive come usare JavaScript per inviare dinamicamente HTTP Requests per scaricare dati (senza ricaricare la pagina!), e come eseguire la **asynchronous programming** necessaria quando si lavora con web requests e altre operazioni che richiedono tempo.

<p class="alert alert-info">Nota che questa lezione assume che tu abbia una familiarita' di base con le RESTful Web API, incluso come leggere e accedere ai loro endpoint. Per un ripasso della terminologia usata nelle API e nelle RESTful requests, vedi il [INFO 201 course reader](https://info201.github.io/apis.html#restful-requests).</p>


## AJAX
Come discusso nel [Chapter 2](#http-requests-and-servers), scarichi data da Internet inviando un **HTTP Request** e poi processando la **response**. Nell'uso quotidiano, gli HTTP Requests sono normalmente inviati dal _browser_ quando l'utente inserisce un URL o clicca un link. Di default, se vuoi scaricare nuovi data, devi far inviare al browser una nuova request, caricando una nuova pagina (o ricaricando la pagina corrente) per mostrare il risultato.

Per creare moderne web page dinamiche che mostrano nuovi data senza dover ricaricare il browser, usiamo una tecnica per inviare HTTP Requests _da codice JavaScript_ invece che dal browser. Questo ci permette di "by-passare" il browser e ottenere nuovi data (e cambiare la web page) senza ricaricarla! Questa tecnica e' chiamata **AJAX** (**A**synchronous **J**avaScript **A**nd **X**ML)&mdash;scriviamo codice che invia una "request con AJAX" o una "AJAX request".

<p class="alert alert-info">_Fun fact_: la tecnologia usata per inviare AJAX requests e' stata sviluppata originariamente da Microsoft a fine anni '90 per supportare la loro giovane versione web dell'app Outlook email/calendar. Le functions JavaScript usate per inviare queste request erano incluse in Internet Explorer come feature _non standard_&mdash;un esempio di browser che aggiunge una nuova funzionalita' che pensa utile ma che non funziona su altre piattaforme. Tuttavia, AJAX ha rapidamente guadagnato popolarita' (in particolare quando Google ha mostrato cosa si poteva fare con Gmail e Google Maps), ed e' diventato uno standard supportato da tutti i browser. Cosi' nascono gli standard!</p>

### XML e JSON {-}
AJAX si chiama "AJA**X**" perche' era stato progettato originariamente per richiedere data in formato XML. **XML** (E**X**tensible **M**arkup **L**anguage) e' un markup language (come HTML) usato per codificare significato nel contenuto in un formato che sia leggibile sia dagli esseri umani _che_ dai computer. La sintassi dell'XML e' _esattamente_ la stessa dell'HTML: infatti, l'HTML puo' essere visto come un "subset" del linguaggio. Puoi pensare all'XML come "HTML, ma puoi inventare i nomi dei tuoi elementi"!

```xml
<!-- Informazioni XML codificate su una persona -->
<person>
   <firstName>Alice</firstName>
   <lastName>Smith</lastName>
   <favorites>
      <music>jazz</music>
      <food>pizza</food>
      <numbers>
          <item>12</item>
          <item>42</item>
      </numbers>
   </favorites>
</person>
```

- Il linguaggio XML non definisce tag specifici come fa HTML; invece spetta alle singole applications determinare quali tag riconoscere e interpretare (e quali tag considerare incomprensibili)&mdash;cio' che viene chiamato [XML Schema](https://en.wikipedia.org/wiki/XML_schema).

All'epoca in cui AJAX e' stato sviluppato, XML era il modo piu' comune per codificare data generici per la trasmissione. E poiche' XML e' un tree di elementi proprio come il DOM, si potevano usare metodi simili per navigare ed estrarre informazioni dal tree. Tuttavia, XML e' un linguaggio molto _verbose_: richiede molti caratteri per codificare le informazioni (quindi la quantita' di data trasferiti e' maggiore), e attraversare un element tree richiede molto codice. Per questo, i developer JavaScript (guidati da [Douglas Crockford](https://en.wikipedia.org/wiki/Douglas_Crockford)) hanno sviluppato un linguaggio alternativo chiamato **JSON** (**J**ava**S**cript **O**bject **N**otation) che e' piu' compatto di XML e puo' essere _direttamente_ parsato in objects e arrays JavaScript:

```json
{
  "firstName": "Alice",
  "lastName": "Smith",
  "favorites": {
    "music": "jazz",
    "food": "pizza",
    "numbers": [12, 42]
  }
}
```

Il formato JSON usa una sintassi quasi identica a quella per definire Object literals in JavaScript, con alcune differenze chiave:

<div class="list-condensed">
- JSON definisce sempre un Object `{}` al "top level".
- Le **keys** degli object JSON (che devono essere stringhe) _devono_ essere scritte tra double-quotes.
- I **values** JSON possono essere solo stringhe, numbers, booleans (`true` o `false`), arrays (`[]`) o altri objects. Non puoi includere una function nel JSON.
- Gli objects e gli arrays JSON non possono avere trailing commas o altri simboli extra&mdash;niente commenti!
</div>

Il linguaggio JavaScript fornisce un object globale `JSON` (come il global `Math`) che puo' essere usato per convertire da _strings_ codificate di contenuto JSON (ad es. il blocco di codice sopra come singola string variable `'{"firstName":"Alice"}'`) a objects JavaScript, e viceversa:

```js
//converti da Object a String codificata
let personObj = {firstName:"Alice", lastName:"Smith", id:12} //JavaScript object
let personString = JSON.stringify(personObj); //trasforma l'object in una JSON string
console.log(personString); //=> '{"firstName":"Alice","lastName":"Smith","id":12}'
console.log(typeof personString); //=> 'string'

//converti da String codificata a Object
let favoritesString = '{"music":"jazz", "numbers":[12,42]}'; //una string, non un object!
let favoritesObj = JSON.parse(favoritesString); //trasforma la JSON string in un object
console.log(favoritesObj); //=> { music: 'jazz', numbers: [ 12, 42 ] }
console.log(typeof favoritesObj); //=> 'object'
```

- Nota che se la tua JSON string non e' formattata correttamente (ad es. manca una virgoletta), la function `JSON.parse()` lancera' un `SyntaxError`. L'errore esatto nella JSON string puo' essere difficile da trovare; gli [online tools](https://jsonformatter.curiousconcept.com/) possono aiutare a mostrare il problema.

JSON ha sostituito XML come encoding preferito per lavorare con AJAX requests&mdash;ma la tecnica e' ancora chiamata "AJAX" ("AJA*J*" non e' facile da dire!)


## Fetching Data
Il supporto AJAX e' integrato nei browser tramite la global variable `XMLHttpRequest` (la "cosa xml http"). Questo object fornisce functions che permettono di inviare un HTTP request al server, ma l'API dell'object e' **davvero complessa da usare**:

<details>
<summary>Un esempio di `XMLHTTPRequest`</summary>
```js
//crea un nuovo object XMLHttpRequest
let request = new XMLHttpRequest();

//configuralo per fare una HTTP GET request verso un URL
request.open('GET', 'https://domain.com/data', true);

//aggiungi un listener per l'event "load" (quando i data sono stati scaricati)
request.addEventListener('load', function() {
    if (request.status >= 200 && request.status < 400) { //controlla lo status della response
        let data = JSON.parse(request.responseText);
        console.log(data); //fai qualcosa con i data
    }
});

//ascolta gli event "error" se c'e' stato un errore di rete
request.addEventListener('error', function() {
//gestisci l'errore...
})

//infine, invia la request al server!
request.send();
```
</details>

Invece di dover capire tutto quel codice, i developer tendevano a usare functions di librerie esterne come [`$.getJSON()`](http://api.jquery.com/jQuery.getJSON/) o [`$.ajax()`](http://api.jquery.com/jQuery.ajax/) di jQuery:

```js
$.getJSON('https://domain.com/data', function(data) {
    //`data` sono i JSON data gia' parsati
    console.log(data); //fai qualcosa con i data
});
```

Ma questo richiede di includere la libreria jQuery nella pagina, e [dato che la necessita' di jQuery sta rapidamente scomparendo](http://youmightnotneedjquery.com/), ora esistono opzioni _built in_ nei browser moderni. In particolare, useremo la API [**`fetch()`**](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API) per inviare facilmente AJAX requests per i data!

<div class="alert alert-warning">
`fetch()` e' uno standard recente, quindi non e' supportato dai browser piu' vecchi (ad es. [Internet Explorer](http://caniuse.com/#feat=fetch)). Tuttavia, possiamo usare comunque `fetch()` con questi browser includendo un [**polyfill**](https://en.wikipedia.org/wiki/Polyfill)&mdash;una libreria esterna che replica una API esistente su piattaforme che non la supportano! Il [`fetch()` polyfill](https://github.com/github/fetch) fornisce una function `fetch()` ai browser che non la includono (lasciando invariati gli altri) e usa l'`XMLHttpRequest` esistente senza che tu debba interagire con quell'object.</p>

Il modo piu' semplice e' caricare il polyfill da un [CDN](https://cdnjs.com/libraries/fetch):

```html
<!-- metti questo PRIMA del tuo script! -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/fetch/2.0.3/fetch.min.js"></script>
```
</div>

La function `fetch()` rende semplice inviare una request: basta chiamarla e passare l'URL dei data che vuoi scaricare:

```js
fetch('https://domain.com/data');
```

<!-- //same origin policy & live-server?? Necessary?? -->

<p class="alert alert-warning">In alcuni browser, non potrai inviare una AJAX request quando la web page viene caricata tramite il protocollo `file://` (ad es. facendo doppio click sul file `.html`). Questa e' una feature di sicurezza per evitare di eseguire per errore un file HTML che contiene JavaScript malevolo che scarica un virus sul tuo computer. Invece, dovresti avviare un web server locale come `live-server` per testare le AJAX requests.</p>

<p class="alert alert-success">Ricorda di usare sempre un **relative path** quando specifichi quale file o API vuoi fetchare. Inoltre, i path sono sempre relativi al file `.html` che l'utente sta visualizzando, non al file `.js` che contiene la chiamata `fetch()`. Quindi fai attenzione se il tuo JavaScript e' in una cartella diversa; il path deve essere relativo all'HTML (che dovrebbe essere nella root del progetto).</p>

## Asynchronous Programming
Tuttavia, la function `fetch()` **NON** restituisce direttamente i data che vuoi scaricare! Scaricare data da Internet puo' richiedere molto tempo: la connessione di rete potrebbe essere lenta e la quantita' di data da scaricare potrebbe essere molto grande (i metadata degli ultimi 100 tweet di Twitter sono quasi 500k di contenuto JSON). Poiche' il fetching dei data puo' richiedere tempo, le AJAX requests sono eseguite **asincronamente** (questa e' la "A" in AJAX)&mdash;il download avverra' _allo stesso tempo_ in cui il resto del codice viene eseguito. Quindi il download e il resto dello script _non_ saranno sincronizzati; saranno "asynchronous".

```js
console.log('Sto per inviare la request'); //statement 1

//invia la request di data all'url
fetch(url);  //statement 2

console.log('Request inviata'); //statement 3

//I data arrivano in realta' in un momento successivo,
//quando l'interpreter JS arriva qui!
```

- Nell'esempio sopra, l'interpreter JS eseguira' lo statement 1, poi lo statement 2 (la chiamata `fetch()`). Passera' poi _immediatamente_ allo statement 3 (il secondo `console.log`), senza aspettare che la request finisca! Il download continuera' in background e finira' a un certo punto piu' avanti nel programma&mdash;anche se non sappiamo esattamente quando.

- E' meglio pensare a `fetch()` come a una function che "_avvia_ il download dei data", non come a una function che scarica effettivamente i data!

Poiche' `fetch()` e' una **asynchronous function** (il suo codice viene eseguito in modo asincrono), restituisce quella che si chiama [**Promise**](https://developer.mozilla.org/en-US/docs/Mozilla/JavaScript_code_modules/Promise.jsm/Promise). Una Promise e' un object che contiene un value che potrebbe non essere ancora disponibile&mdash;puoi pensare a una Promise come a un placeholder dove il risultato della chiamata asincrona verra' eventualmente memorizzato (e' una "promessa" di avere dei data, ma la promessa puo' essere mantenuta o disattesa!).

- Le Promises sono il modo moderno di gestire le asynchronous functions, ma essendo parte dello standard ES6 [non sono ancora disponibili su tutti i browser](http://caniuse.com/#feat=promises) (in particolare: Internet Explorer). Quindi dovrai includere [_un altro polyfill_](https://github.com/stefanpenner/es6-promise) per supportare IE. E' disponibile anche da un [CDN](https://cdnjs.com/libraries/es6-promise).

Le Promises hanno tre stati possibili: _pending_ (i data si stanno scaricando), _fulfilled_ (i data hanno finito di scaricarsi) o _rejected_ (il download e' fallito e la promise e' "rotta"). Possiamo specificare _callback functions_ (simili agli event listeners) che si eseguono quando una Promise pending viene fulfilled oppure rejected. La callback "on success" si specifica chiamando la function **`.then()`** sull'object Promise e passando la "on success callback" come parametro:

```js
function onSuccessCallback(response) { //cosa fare quando otteniamo la response
    console.log(response);
}

//Quando e' fulfilled, esegui la callback function (a cui verra' passata la response)
let promise = fetch(url);
promise.then(onSuccessCallback);

//E' molto piu' comune usare variables/callback anonime:
fetch(url).then(function(response) {
    console.log(response);
});
```

La callback "on success" ricevera' un singolo parametro: il **data value** per cui la Promise era stata creata (ad es. i data che verranno scaricati da `fetch()`). Quindi quando la callback viene eseguita, avrai accesso ai data! Per esempio, quando la Promise di `fetch()` viene fulfilled, passera' un object che rappresenta la _response_ all'HTTP Request:

```js
let promise = fetch(url);
promise.then(function(response){
    console.log( response.url ); //una stringa di dove e' stata inviata la request
    console.log( response.status ); //il codice di status HTTP (ad es. 200, 404)
});
```

Questo response object ha una property `body` che rappresenta il "body" (data content) della HTTP response. Tuttavia, quel body e' memorizzato come "stream" di 0 e 1, non come un object JavaScript (o anche solo una string che puoi `JSON.parse()`)! Per ottenere il body in un formato utilizzabile, devi "encodarlo" in un object JavaScript chiamando il metodo **`.json()`**.

- Esiste anche un metodo equivalente `.text()` per encodare il response body in plain text.

### Chaining Promises {-}
**Ma c'e' un problema**: il processo di "encoding" fatto da `.json()` puo' richiedere tempo (in particolare per una grande quantita' di data). Quindi, invece di bloccare (mettere in pausa) il resto del programma mentre l'encoding avviene, il metodo `.json()` restituisce _un'altra Promise_ come placeholder di quando il body encodato sara' disponibile! Quindi dovrai specificare una callback `.then()` anche per _quella_ Promise.

Tuttavia, la function `.then()` di una Promise ha una proprieta' interessante che rende tutto piu' semplice. Chiamare `.then()` su una Promise restituisce una nuova Promise come placeholder per i data prodotti dalla function `.then()`. Questi data promessi saranno il value _restituito_ dalla callback "on success". Questo permette di "chainare" le chiamate `.then()`, ognuna delle quali puo' eseguire una trasformazione sui data:

```js
function makeQuestion(dataString) { //una function che trasforma una stringa in una domanda
    return dataString + '???';
}

//immagina una function asincrona ipotetica `getAsyncString`
//restituisce una Promise (placeholder) per una stringa caricata da una fonte data
let originalPromise = getAsyncString(myDataSource);

//quando la promise originale e' fulfilled, chiama `makeQuestion` su di essa
//`questionPromise` sara' un placeholder per quei data trasformati
let questionPromise = originalPromise.then(makeQuestion);

//quando `questionPromise` e' fulfilled, chiama una callback anonima su di essa
//alla callback verranno passati i data trasformati ("question")
questionPromise.then(function(data){
    console.log(data); //i data saranno una domanda!
})
```

Piu' comunemente, usiamo _anonymous variables_ per le promises successive, permettendoti di chainarle in un modo che quasi si legge come inglese!

```js
getAsyncString()
    .then(makeQuestion)
    .then(function(data){
        console.log(data);
    });
```

Ma aspetta, c'e' di piu'! `.then()` ha anche una feature speciale: se la callback "on success" restituisce una _Promise_ (invece di un altro tipo di value), allora la promise "esterna" assumera' lo stato di quella nuova Promise restituita. Questo significa che puoi semplicemente _restituire_ una Promise dentro una callback `.then()`, e quella Promise diventera' l'oggetto della chiamata `.then()` successiva:

```js
let outerPromise = getAsyncString(myFirstSource).then(function(firstData){
    //fai qualcosa con `firstData`

    let newPromise = getAsyncString(mySecondSource); //una seconda async call!
    return newPromise; //return della promise.
}); //`outerPromise` ora assume lo stato e i data di `newPromise`

outerPromise.then(function(secondData){
    //fai qualcosa con `secondData`, i data scaricati da `mySecondSource`
});
```

Tornando a `fetch()` per mettere tutto insieme: dato che la function di encoding `.json()` restituisce una Promise, puoi semplicemente _restituire_ quella Promise dalla callback `.then()` per renderla disponibile alle successive chiamate `.then()`!

```js
fetch(url)  //avvia il download
    .then(function(response) {  //quando ha finito di scaricare
        let dataPromise = response.json();  //avvia l'encoding in un object
        return dataPromise;  //passa su questa Promise
    })
    .then(function(data) {  //quando ha finito di codificare
        //fai qualcosa con i data!!
        console.log(data); //ora sara' codificato come un object JavaScript!
    });
```

Questo esempio di codice ti permette di scaricare i data e encodarli in un normale object JavaScript con cui puoi lavorare.

### Handling Errors {-}
Quando scarichi data da Internet, e' sempre possibile che la HTTP request fallisca. La request potrebbe essere inviata all'URL sbagliato, il computer del client potrebbe avere problemi di connessione, oppure il server potrebbe avere problemi.

Per gestire errori inevitabili, le Promises forniscono un metodo **`.catch()`** usato per specificare una callback da eseguire se la Promise viene _rejected_ (si verifica un errore). Questa callback ricevera' un [Error object](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error) con i dettagli dell'errore.

```js
fetch(url)
    .then(function(response) {  //quando ha finito di scaricare
        return response.json();  //la seconda promise e' anonima
    })
    .then(function(data) {  //quando ha finito di codificare
        //fai qualcosa con i data!!
        console.log(data); //ora sara' codificato come un object JavaScript!
    })
    .catch(function(err) {
        //fai qualcosa con l'errore
        console.error(err);  //ad es. mostra in console
    });

```

- E' importante: il metodo `.catch()` "cattura" gli errori di _tutte le Promises precedenti_ nella catena `.then()`! Questo significa che il `.catch()` sopra mostrera' sia gli errori nel download (`.fetch()`), sia gli errori nell'encoding del body (`.json()`).

- Quasi sempre vorrai mostrare l'errore all'utente in qualche modo, ad esempio creando un elemento [alert](http://getbootstrap.com/docs/4.0/components/alerts/) nel DOM.

- La function `.catch()` restituisce _anche_ una Promise, quindi puoi continuare a chainare `.then()` dopo. Queste callback successive verranno eseguite solo se nessuna Promise precedente e' stata rejected (cioe' se non ci sono stati errori).

**Importante**: una Promise viene rejected solo se c'e' un vero "Error" nell'invio della request. Se il server risponde con un errore [401](https://httpstatuses.com/401) (ad es. non hai il permesso di accedere alla risorsa) o con il messaggio "invalid API key", questo non verra' gestito da `.catch()`. Dal punto di vista di JavaScript, la request e' andata a buon fine&mdash;non e' colpa di fetch se i data che hai richiesto non sono quelli che volevi!

- Puoi usare le properties `response.status` e `response.ok` per controllare lo status della HTTP response.

Quindi, vorrai assicurarti di gestire risposte errate o response body inattesi, sia nei test della tua application (per assicurarti che la request sia inviata all'URL corretto) sia quando gestisci l'input dell'utente.


<!-- TODO
## async/await
//questo ti permette di scrivere codice asincrono in uno stile piu' "sincrono", specificando righe che verranno eseguite solo dopo che la promise e' risolta (fulfilled o rejected).

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/async_function
https://hackernoon.com/6-reasons-why-javascripts-async-await-blows-promises-away-tutorial-c7ec10518dd9
-->


<!--
//qui vanno i form... oppure segui l'esercizio per crearne uno!
    //form: `method` and `action`
    //input elements
    //labels
    //aria
    //preventing default
-->

### Altri Data Formats {-}
L'uso di `fetch()` sopra funziona bene per i data formattati in JSON (che e' il formato piu' comune per data accessibili via web). Tuttavia, potresti voler caricare dinamicamente data in un formato diverso, come plain text o valori separati da virgola (CSV). Ci sono diversi modi per supportare questo:

Per scaricare data in formato **plain text**, puoi usare `fetch()` come sopra, ma invece di chiamare `.json()` sulla response per encodarla come object JavaScript, puoi chiamare il metodo `.text()` per encodarla come string di base:

```js
fetch(url)  //avvia il download
    .then(function(response) {  //quando ha finito di scaricare
        let dataPromise = response.text();  //avvia l'encoding in una String
        return dataPromise;  //passa su questa Promise
    })
    .then(function(text) {  //quando ha finito di codificare
        //fai qualcosa con i data testuali!!
        console.log(text); //ora sara' codificato come una stringa JavaScript!
    });
```

L'encoding come text supporta _qualsiasi_ plaintext formated data&mdash;che provenga da un file `.txt`, un file `.csv`, o perfino un file `.json` o `.js`! In effetti, se encodi data JSON come plain text usando il metodo `.text()`, puoi poi parsarli esplicitamente in un Object JavaScript usando la function built-in [`JSON.parse()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/parse) descritta sopra!

Anche se il metodo `.text()` encodera' i data in una String JavaScript, quella String avra' spesso un formato particolare che deve essere **parsed** (interpretato) per rendere i data utili. Per esempio, una String in formato CSV non e' molto utile da sola; dovresti parsarla in un array di objects (dove ogni object rappresenta una row) per analizzare i data.

E' possibile ([ma complesso](https://stackoverflow.com/a/8497474)) fare questo parsing usando functions built-in sulle String (assumendo che i tuoi data CSV rispettino gli standard ufficiali), ma in generale e' piu' semplice ed efficace usare una libreria esterna per questo parsing. Una delle migliori librerie per questo lavoro e' [**`d3.dsv()`**](https://github.com/d3/d3-fetch), un componente della libreria di visualizzazione [d3](https://d3js.org/). `d3.fetch()` fornisce convenience wrapper functions per `fetch()` che eseguono anche un parsing efficace dei data.

Per usare `d3.fetch()`, devi caricarlo come libreria esterna:

```html
<script src="https://d3js.org/d3-dsv.v1.min.js"></script>
<script src="https://d3js.org/d3-fetch.v1.min.js"></script>
```

(Maggiori dettagli in arrivo...)
<!-- (the `d3-fetch` )



```
'{"name":"Ada Smith", "age": }'
```


Per plaintext formattato (come JSON o CSV), dovrai -->






## Risorse {-}
<div class="list-condensed">
- [An Introduction to AJAX for Front-End Developers (tuts+)](https://webdesign.tutsplus.com/tutorials/an-introduction-to-ajax-for-front-end-designers--cms-25099)
- [An Introduction to `fetch()` (Google)](https://developers.google.com/web/updates/2015/03/introduction-to-fetch)
- [JavaScript Promises: an Introduction (Google)](https://developers.google.com/web/fundamentals/primers/promises)
</div>

<!-- http://papaparse.com/ <- csv parsing -->
