# Layout CSS

I capitoli precedenti hanno discusso come usare CSS per specificare l'aspetto dei singoli elementi HTML (per esempio, dimensione del testo, colore, background, ecc.). Questo capitolo dettaglia come usare CSS per dichiarare dove gli elementi HTML dovrebbero _apparire_ su una web page! Posizionare gli elementi esattamente come li vuoi puo' essere sorprendentemente difficile. Gli elementi sono disposti a partire dall'**angolo in alto a sinistra** della pagina, e sono organizzati in base a tre concetti correlati (ma distinti):

- **Display**: determina come gli elementi condividono lo spazio orizzontale
- **Position**: permette di regolare la posizione del flow naturale degli elementi
- **Box-model**: descrive la quantita' di spazio 2D occupata da un elemento e quanto spazio c'e' tra gli elementi

## Display




## Position


## Risorse {-}
<div class="list-condensed">
- [Il Box Model (MDN)](https://developer.mozilla.org/en-US/docs/Learn/CSS/Introduction_to_CSS/Box_model)
- [Il CSS Box Model (CSS-Tricks)](https://css-tricks.com/the-css-box-model/)
- [Guida completa a Flexbox](https://css-tricks.com/snippets/css/a-guide-to-flexbox/) La migliore spiegazione delle properties Flexbox che troverai.
- [Guida completa a Grid](https://css-tricks.com/snippets/css/complete-guide-grid/) Una spiegazione simile, ma per il framework Grid (non discusso qui).
</div>
