# ES6+ Syntax {#es6}
Come discusso nel [Chapter 10](#history-and-versions), la specifica ECMAScript per il linguaggio JavaScript ha attraversato diverse versioni, ognuna delle quali ha aggiunto nuova sintassi e nuove feature per rendere il linguaggio piu' potente, espressivo o piu' facile da usare.

Dopo che il linguaggio JavaScript fu scritto inizialmente nel 1995 e poi iterato fino alla fine degli anni '90, rimase per lo piu' consistente (con piccoli cambiamenti) per circa un decennio&mdash;fino al 2009 con il rilascio di JavaScript v5. La versione successiva importante non usci' fino al 2015&mdash;anche se ufficialmente chiamata "ECMAScript 2015", la maggior parte dei developer la chiama con il nome di lavoro **"ES6"** (ad es. versione 6 del linguaggio). ES6 ha introdotto molte feature sintattiche notevoli e utili&mdash;inclusi `let` e `const`! Da allora, il linguaggio e' stato aggiornato annualmente, con ogni versione chiamata secondo l'anno di rilascio (_ES 2016_ e' uscito nel 2016, _ES 2017_ nel 2017, ecc).

Questo capitolo introduce alcune delle feature piu' notevoli e utili introdotte in ES6 e nelle versioni successive di JavaScript&mdash;in particolare quelle necessarie quando si usa il framework React (discusso nei capitoli seguenti).

<p class="alert alert-warning">A questo punto ES6 e' sufficientemente maturo da essere [quasi completamente supportato dai browser moderni](https://compat-table.github.io/compat-table/es6/), con l'eccezione significativa di Internet Explorer. Tuttavia, l'interpreter JavaScript nei browser piu' vecchi (e in IE) non riconosce la nuova sintassi introdotta in questa versione. Invece, dovresti convertire quel codice in equivalente ES5 (o precedente), che puo' essere interpretato. Un modo per farlo e' usare il compiler [Babel](https://babeljs.io/), che "_transpila_" il codice JavaScript da una versione a un'altra. Il capitolo successivo discute come fare questo tipo di transpiling con React (spoiler: e' fatto automaticamente dai build tools forniti), ma e' anche possibile [installare](https://babeljs.io/docs/setup/#installation) e usare Babel da soli.</p>


## ES6+ Syntax Features

> Syntactic Sugar causes cancer of the semicolon - [Alan Perlis](http://www.cs.yale.edu/homes/perlis-alan/quotes.html)

Molte delle feature ES6 sono _syntactic shortcuts_&mdash;forniscono sintassi per scrivere functions e operazioni in modo piu' conciso. Queste feature non sono necessarie per scrivere JavaScript, ma possono rendere il codice piu' facile da scrivere e da leggere (una volta appresa la sintassi), e sono considerate il modo "normale" di scrivere JavaScript moderno. Questa sezione discute alcune delle feature sintattiche piu' comuni.


### Arrow Functions {-}
Come descritto nel [Chapter 11](#functional-programming), JavaScript permette di definire functions come _anonymous values_:

```js
const sayHello = function(name) {
  return 'Hello '+name;
}
```

Come hai visto, l'uso di anonymous functions e' incredibilmente comune in JavaScript, soprattutto quando usate come anonymous callbacks. Proprio per questo, ES6 ha introdotto una sintassi piu' semplice e concisa per specificare rapidamente anonymous functions. Anche se ufficialmente chiamate [lambda functions](https://en.wikipedia.org/wiki/Anonymous_function), sono piu' comunemente note come [**arrow functions**](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions), per via dell'uso del simbolo "arrow" **`=>`**:

```js
const sayHello = (name) => {
    return 'Hello '+name;
}
```

Per trasformare una anonymous function in _arrow function_, basta rimuovere la keyword `function` dalla definizione e mettere un arrow `=>` tra la lista dei parametri e il block (indicando che la lista dei parametri "va verso" il block successivo). Questo fa risparmiare qualche carattere quando digiti!

E' anche possibile omettere le `()` attorno alla lista degli argomenti in una arrow function:

```js
//may omit the parentheses around the argument -- but don't do this!
const sayHello = name => {
    return 'Hello '+name;
}

//requried to include the parentheses if there are no arguments
const printHello = () => {
    console.log('Hello world');
}
```

Tuttavia, questo rende la sintassi piu' difficile da leggere (leggendo il testo, sembra una dichiarazione di variable finche' non arrivi al `=>`). Quindi dovresti includere sempre le parentesi `()` nella lista dei parametri: aiuta la leggibilita' e rende piu' facile aggiungere parametri in seguito&mdash;rispettando i requisiti di [good code style](#code-style-guide).

Le arrow functions sono particolarmente comode quando usi anonymous callback functions (function literals):

```js
const array = [1,2,3]; //an array to work with

//function declaration syntax
array.map(function(num) {
  return num * 2; //multiply each item by 2
});

//arrow function syntax
array.map((num) => {
  return num * 2; //multiply each item by 2
});
```

Usare una arrow function rende leggermente piu' ovvio che la function prende un input e poi produce (`=>`) un output&mdash;cosi' puoi concentrarti sul metodo di interesse (come `.map()`) invece che sulla callback. Tuttavia, rende meno ovvio che l'argomento di `.map()` e' una _function_ finche' non ti abitui a riconoscere la freccia `=>`.

<p class="alert alert-info">Le arrow functions sono _lexically scoped_, cioe' il value della keyword `this` viene mantenuto anche dentro la function. Questo puo' essere importante in alcuni contesti (come le [classes](#es6-classes)) ed e' uno dei motivi per cui e' meglio usare arrow functions quando definisci callback functions).</p>

Per functions molto semplici, le arrow functions possono essere scritte in modo ancora piu' _compatto_: se il body della function ha solo uno statement, puoi omettere le `{}` del block e anche il `return`. Questa si chiama **concise body**. La function restituira' il risultato del singolo statement, che sara' un'espressione o `undefined`. Per esempio:

```js
//function declaration syntax
function makeFullName(first, last) {
  return first + " " + last;
}

//block body arrow function syntax
const makeFullName = (first, last) => {
  return first + " " + last;
}

//concise body arrow function syntax
const makeFullName = (first, last) => first + " " + last;
```

Nota che se l'espressione di una concise-body arrow function restituisce `undefined` (ad es. da un `console.log`), allora anche la arrow function restituira' `undefined`.

```js
//concise body arrow function syntax
const sayHello = (name) => console.log("Hello" + name);

//that is identical to use block body syntax. Yes, returning the result of
//console.log() is odd
const sayHello = (name) => {
  return console.log("Hello" + name);
}
```

Usare la concise body synatx potrebbe farti risparmiare qualche carattere (e anche line break!). Tuttavia, puo' rendere la function _piu' difficile da leggere_&mdash;soprattutto quando ha piu' di un argomento&mdash;e piu' difficile da riconoscere come function perche' il block non e' evidente. Le concise body functions sono anche _piu' difficili da modificare_&mdash;possono avere solo uno statement, quindi se vuoi che la function faccia piu' di una cosa&mdash;incluso usare un loop o uno `if` statment&mdash;devi comunque convertirla in block body. (Cercare di rendere quell'unica espressione molto complessa e' anche poor style). E dato che non puoi aggiungere righe, e' _piu' difficile fare debug_ perche' non puoi aggiungere `console.log` o altri passi di debugging. Per questo, dovresti quasi mai usare la concise-body arrow function syntax se non per callback molto semplici&mdash;e' sempre meglio usare la block body syntax.


In generale, le arrow functions (in particolare le block body arrow functions) sono un clean syntactic shortcut che e' il modo "normale" di scrivere anonymous callback functions&mdash;le vedrai in tanti esempi e nel codice professionale. Le "top-level" functions dovrebbero essere scritte con la sintassi regolare di function declaration, ma le callback functions dovrebbero _sempre_ essere scritte usando block-body arrow functions.


### Destructuring {-}
ES6 ha introdotto anche i [**destructing assignments**](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment), che ti permettono di assegnare ogni elemento di un array (o ogni property di un object) a variables separate in un'unica operazione. Si chiama "destructuring" perche' stai "unpacking" i values di un array in un insieme di variables.

Per fare destructuring di un array in JavaScript, scrivi le variables a cui vuoi assegnare i values dentro parentesi quadre **`[]`** sul _left-hand side_ dell'assegnazione&mdash;quasi come se stessi assegnando a un array!

```js
const myArray = [1, 2, 3];
const [x, y, z] = myArray; //assign myArray elements to `x`, `y`, `z` respectively
console.log(x); //=> 1;
console.log(y); //=> 2;
console.log(z); //=> 3;
```

Quando fai destructuring di un array, i values sono assegnati _in ordine_&mdash;il value all'index 0 va alla prima variable, il value all'index 1 alla seconda, ecc.

E' possibile che la "lista di variables" e la size dell'array destructured non corrispondano. Se nell'array ci sono piu' values che variables, i values extra non verranno assegnati (saranno ignorati). Se ci sono piu' variables che values, le variables in eccesso saranno `undefined` (perche' il value in quella posizione dell'array e' `undefined`).

```js
const bigArray = [1, 2, 3, 4, 5];
const [a, b] = bigArray; //only the first 2 elements will be assigned
console.log(a); //=> 1;
console.log(b); //=> 2;
//other elements are not assigned

const smallArray = [1, 2]
const [x, y, z] = smallArray;
console.log(x); //=> 1;
console.log(y); //=> 2;
console.log(z); //=> undefined; (because smallArray[2] is undefined!)
```

E' anche possibile fare destructuring di _objects_ usando una sintassi simile, tranne per il fatto che metti le variables a cui vuoi assegnare dentro **`{}`** sul _left-hand side_ dell'assegnazione&mdash;come se stessi assegnando a un object!

```js
const myObject = {a: 1, b: 2, c: 3};
const {a, b, c} = myObject;
console.log(a); //=> 1; myObject.a
console.log(b); //=> 2; myObject.b
console.log(c); //=> 3; myObject.c
```

Nota che quando fai destructuring di un object, le variables specificate sul lato sinistro dell'assegnazione ricevono il value della _property_ corrispondente nell'object. Quindi in `const {a, b, c} = myObject`, la `a` viene assegnata a `myObject.a`, la `b` a `myObject.b`, ecc. L'ordine degli elementi su entrambi i lati dell'equazione non conta, perche' le object properties sono unordered!

```js
const myObject = {a: 1, b: 2, c: 3};
const {c, b, a} = myObject; //"order" of variables doesn't matter
console.log(a); //=> 1
console.log(b); //=> 2;
console.log(c); //=> 3;
```

Esiste anche sintassi per assegnare properties dell'object a nomi di variable diversi (vedi [la documentazione sul destructuring](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment#Object_destructuring) per dettagli).

Come per il destructuring di array, la lista di variables e il numero di object properties non devono per forza coincidere. Le properties non abbinate non verranno assegnate a variables, e le variables senza property corrispondenti resteranno `undefined`.

Il destructuring e' uno syntactic shortcut utile per fare assegnazioni multiple. In React e' spesso usato per creare variables locali, cosi' non devi scrivere continuamente `object.property`:

```js
//a function that expects an object as an argument
function getBMI(personObject) {
  const {height, weight} = personObject; //destructure to local variables
  //this avoids needing to refer to `personObject.height`

  return 703*weight/(height*height); //calculate and return value
}

const person = {name: 'Ada', height: 64, weight: 135} //an example person
const adaBMI = getBMI(person); //pass in the object
```

In effetti, questo comportamento e' cosi' comune che e' possibile _fare destructuring dei function parameters_ nella function declaration stessa! Per farlo, sostituisci il nome dell'object nella lista dei parametri con l'insieme delle variables destructured (cio' che starebbe sul left-hand side del destructuring):

```js
//a function with the object argument destructured
//notice the `{} in the argument list`
function getBMI( {height, weight} ) { //implicitly calls `{height, weight} = personObject`

  return 703*weight/(height*height); //calculate and return value
}

const person = {name: 'Ada', height: 64, weight: 135} //an example person
const adaBMI = getBMI(person); //pass in the object
```

Per essere chiari: nel secondo esempio, la function `getBMI()` si aspetta _solo 1 argomento_&mdash;quell'unico argomento viene semplicemente destructured in due variables quando la function viene chiamata.

Questa sintassi puo' farti risparmiare una riga di codice, ma puo' anche rendere piu' facile fraintendere la function e pensare che prenda piu' argomenti di quanti ne prenda davvero (se ti sfuggono le `{}` nella lista dei parametri). D'altro canto, questa sintassi rende chiaro esattamente quali properties deve avere l'object atteso&mdash;questa function definisce chiaramente la sua API: il "person object" deve avere `height` e `weight` (e non solo, ad es., `name` o `age`). Come per ogni sintassi alternativa, ci sono trade-off in termini di code style e leggibilita'. Tuttavia, questa forma di sintassi e' spesso usata in React (dove molte functions si aspettano un singolo object, ma devi accedere alle properties individuali).


### Spreading {-}
Introdotto in ES6 e poi ampliato in ES 2018, lo [**spread operator**](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_operator) (l'ellissi **`...`**) ti permette di riferirti a "gli elementi di" un array o object esistente quando dichiari un nuovo value. "Espande" i contenuti dell'array o dell'object nel nuovo value. Lo scrivi come unary operator, mettendo i tre punti davanti al value che vuoi espandere:

```js
const originalArray = ['a', 'b', 'c', 'd'];

//new array contains "the elements of" `originalArray`
const newArray = [...originalArray, 'e', 'f'];

console.log(newArray) //['a', 'b', 'c', 'd', 'e', 'f']
```

In questo esempio il `newArray` contiene tutti gli elementi di `originalArray`, oltre a elementi aggiuntivi. E' particolarmente utile quando vuoi creare una "copy" di un array o object, con o senza values aggiuntivi.

```js
//assigning an array to a different variable doesn't create a new array!
const myArray = ['a', 'b', 'c', 'd'];
const secondArray = myArray; //just a new label for the same value
myArray[0] = 'Z'; //changing the original variable changes second variable as well
console.log(secondArray[0]) //'Z'

//use spread to create an actual copy that is a different array
const clonedArray = [...myArray];
myArray[1] = 'Q'; //modify the original variable
console.log(clonedArray[1]); //'b'; the clonedArray is different
```

Lo spread operator puo' essere usato anche per creare nuovi objects; fare spread di un object espande sia le property keys che i values:

```js
const person = {name: 'Ada', height: 64, weight: 135}

const copyOfPerson = {...person}; //clone the object
console.log(copyOfPerson); // {name: 'Ada', height: 64, weight: 135}

//all off the properties are "spread" into the new object
const personWithHat = {hat: 'bowler', ...person}
console.log(person); //has properties 'name', 'height', 'weight'
console.log(personWithHat); //has properties 'hat', 'name', 'height', 'weight'
```

Quando combinato con il _destructuring_, lo spread operator puo' riferirsi anche al "resto" degli elementi di un array o object che non sono stati assegnati a specifiche variables. In questa situazione spesso si parla di **rest operator**.

```js
const dimensions = [10, 20, 30, 40];
//extra values are "spread" into destructuring slots
const [width, height, ...others] = dimensions
console.log(width);  //=> 10
console.log(height); //=> 20
console.log(others);   //=> [30, 40]; the rest of the values!
```

Infine, lo spread operator puo' essere usato per specificare che una function puo' accettare un numero variabile di argomenti e raccogliere tutti questi values in un singolo array. Lo fai includendo lo spreading operator nella function declaration. Gli argomenti verranno raccolti in quella singola variable&mdash;quasi il contrario del destructuring! (E si', il fatto che lo "spread" operator "raccolga" i values e' un po' confuso).

```js
//a function that logs out all of the arguments
function printArgs(...argArray){
    //all the arguments will be grouped into a single array `args`
    for(const arg of argArray) {
      console.log(arg); //can log out all of them, no matter how many!
    }
}

printArgs('a', 'b', 'c'); //=> "a" "b" "c"
printArgs(1, 2, 3, 4, 5, 6); //=> "1" "2" "3" "4" "5" "6"


//a function that adds up all the arguments (no matter how many!)
function sum(...numbers) {
    //numbers is an array, so we can `reduce()` it!
    const total = numbers.reduce((runningTotal, num) => {
        return runningTotal + num; //new total
    }, 0); //start at 0

    return total;

    //or as one line with a concise arrow function (not pretty!)
    return numbers.reduce((total, n) => total+n);
}

sum(3 ,4, 3); // => 10
sum(10, 20, 30, 40); // => 100
```

Lo spread operator non e' usato spesso in questo modo con React, ma e' utile saperlo!


### Template Strings {-}
In ES6, puoi dichiarare Strings che contengono espressioni embedded, permettendoti di "iniettare" un'espressione direttamente in una string (invece di concatenare la String con quell'espressione). Queste si chiamano [**template strings**](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals) (o _template literals_). Le template strings si scrivono con i back tick (**``` `` ```**) invece delle quotes, con le espressioni inserite dentro il token **`${}`**:

```js
const name = 'world';
const greeting = `Hello, ${name}!`; //template string
console.log(greeting); //=> "Hello, world!"
```

Le template strings possono anche includere line break, permettendoti di creare stringhe multi-linea!

Nota che puoi mettere _qualsiasi_ espressione dentro il token `${}`; tuttavia, e' best practice mantenere l'espressione il piu' semplice possibile (ad es. usando una variable locale) per supportare la leggibilita':

```js
const name = 'world';

//greeting with capitalization. Don't do this!
const greeting = `Hello, ${name.substr(0,1).toUpperCase() + name.substr(1)}!`
console.log(greeting); //=> "Hello, World!";

//do this instead!
const capitalizedName = name.substr(0,1).toUpperCase() + name.substr(1);
const greeting = `Hello, ${capitalizedName}`
console.log(greeting); //=> "Hello, World!";
```

One more example:

```js
//function expects a name, an animal, and a verb
function makeExcuse(name, animal, verb) {
  const email = `Hello Professor ${name},

Please excuse my missing assignment, as my ${animal} ate it.

${verb} you later,
A Student`;

  return email;
}

const excuse = makeExcuse('Ross', 'Lemur', 'Smell');
```


## Modules
Finora hai probabilmente scritto tutto il codice JavaScript in un singolo file di script (ad es. `index.js`), anche se hai incluso altre librerie come Bootstrap o JQuery tramite tag `<script>` aggiuntivi. Ma man mano che le application diventano piu' grandi e complesse, questo singolo file puo' diventare rapidamente ingestibile con centinaia o migliaia di righe di codice che implementano decine di feature. File cosi' grandi diventano difficili da leggere e fare debug ("dov'era definita quella function?"), possono introdurre problemi con il global namespace condiviso ("ho gia' dichiarato una variable `user`?"), e in generale mescolano il codice in modo che viola il principio di _Separation of Concerns_.

La soluzione a questo problema e' dividere il codice dell'applicazione in **modules** (script) separati, ciascuno responsabile di un pezzo specifico di funzionalita'. E invece di caricare ogni module con un tag `<script>` separato (con possibili problemi di ordering e dependency, oltre a inquinare il global namespace), puoi definire ogni module come script autonomo che "importa" esplicitamente le functions e le variables di cui ha bisogno da altri moduli. Questo ti permette di organizzare meglio il programma man mano che cresce.

Anche se separare il codice in moduli e' comune in ambiente Node.js, ES6 aggiunge una sintassi che permette di trattare i singoli file `.js` come moduli che possono comunicare tra loro. Questi sono noti come [**ES6 Modules**](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules).


Un browser carica i moduli in modo diverso dagli script "regolari"; per caricare codice come module, specifichi l'attribute `type="module"` nel tag `<script>` di quel module:

```html
<!-- load scripts that can import from other modules -->
<script type="module" src="path/to/firstModule.js"></script>
<script type="module" src="path/to/secondModule.js"></script>
```

<p class="alert alert-warning">Per motivi di sicurezza, i moduli non possono comunicare quando una web page e' accessibile tramite protocollo `file://`. Per usare i moduli, devi accedere alla pagina tramite un web server, ad esempio usando un [development server](#development-server) come `live-server`.</p>

Tuttavia, nella maggior parte dei casi _non_ userai i moduli direttamente nel browser. Invece, i moduli verranno caricati e compilati tramite un build tool esterno come [webpack](https://webpack.js.org/). In queste situazioni userai il _module loader_ fornito dal runtime JavaScript di Node. Questo loader introduce alcune particolarita' di sintassi, che sono indicate nella spiegazione della sintassi.

<div class="alert alert-info">Questa sezione descrive gli ES6 modules, usati nelle web applications (in quanto parte della specifica ECMAScript). Tuttavia, Node.js usa di default un sistema alternativo di caricamento dei moduli chiamato [CommonJS](https://nodejs.org/docs/latest/api/modules.html#modules_modules). Questo usa il metodo built-in `require()` per caricare un module (che restituisce una singola variable "exported"). I values vengono esportati da un module assegnandoli al global `module.exports`. Questo corso usera' esclusivamente ES6 Modules&mdash;non usare `require()`&mdash;ma e' bene conoscere l'approccio alternativo CommonJS quando cerchi aiuto.</div>


### Module Syntax {-}
Come in Java o Python, un module JavaScript puo' "caricare" moduli o librerie esterne usando la keyword **`import`**:

```java
//Java example: import the `Random` variable from `java.util` module
import java.util.Random;
```

```python
# Python example: import the `randint` variable from `random` module
from random import randint
```

```js
//JavaScript:
//import the `Random` variable from a `util.js` module
import { Random } from './util.js';

//import the `randint` and `randrange` variables from a `random.js` module
import { randint, randrange } from './random.js'
```

Questa e' la versione piu' comune della sintassi `import` di ES6 (chiamata **named import**): scrivi la keyword `import`, seguita da un set di braces `{ }` contenente una sequenza di variables separate da virgola che vuoi "importare" da un module specifico. Segue la keyword `from`, seguita da una string che contiene il **relative path** allo script del module da importare. Nota che nei sistemi basati su Node (come l'ambiente di build React) includere l'estensione del module e' opzionale (di default il module loader cerca file che finiscono in `.js`).

- Assicurati di includere `./` per indicare che stai caricando un file da una directory specifica. Se lo ometti, il module loader di Node cerchera' un module installato nel _load path_ (ad es. in `node_modules/`). Ommetti `./` quando carichi librerie di terze parti come jQuery o React:

    ```js
    //with jquery installed in `node_modules/`
    //import the `$` and `jQuery` variables
    import { $, jQuery } from 'jquery'; //no `./` in front of library name
    ```

Nota che le variables importate da un module possono essere di qualsiasi tipo&mdash;strings, objects e, piu' spesso, functions.


Qualsiasi variable che un module `import` deve essere dichiarata come disponibile nel module da cui proviene&mdash;simile all'uso della keyword `public` in Java. Per farlo, **exporti** la variable (cosi' puo' essere "imported" altrove) usando la keyword **`export`**, posta davanti alla dichiarazione della variable:

```js
/*** my-module.js ***/

//define and export variables for use elsewhere
export const question = "Why'd the chicken cross the road?";
export const answer = "To get to the other side";

export function laugh() { //an exported function
    console.log("hahaha");
}
```

Questo si chiama **named export** (in contrasto con il _default export_ descritto sotto). Una volta che le variables sono state exportate, possono essere importate da un altro file di script:

```js
/*** index.js ***/

//import all 3 variables from `my-modules.js`
//now all 3 variables exist in this module and can be used
import { question, answer, laugh } from './my-module.js';

console.log(question); //=> "Why'd the chicken cross the road?"
console.log(answer); //=> "To get to the other side"
laugh(); //"hahaha"
```

Importante: _solo_ le variables che `export` sono rese disponibili agli altri moduli! Qualsiasi cosa che non ha quella keyword non sara' disponibile&mdash;rimarra' "private" al suo module. La best practice e' `export`are solo i values che sai serviranno ad altri moduli.

Quella sopra e' la sintassi di base per usare _named_ imports ed exports. Ma ci sono altre opzioni sintattiche quando usi `import` e `export`.

Per esempio, puoi usare la keyword **`as`** per "aliasare" un value sia quando viene exportato (cosi' e' condiviso con un nome diverso) sia quando viene importato (cosi' viene caricato e assegnato con un nome diverso). Questo e' particolarmente utile quando vuoi produrre una API pulita per un module (cosi' `export`i values con nomi consistenti, anche se internamente usi altri nomi), o quando vuoi `import`are una variable con un nome molto lungo.

```js
/*** my-module.js ***/
export function foo() { return 'foo'; } //standard named export

//provide an "alias" (consumer name) for value when exporting
export { bar as yourBar };

//will not be available (a "private" function)
function baz() { return 'baz'; }
```

```js
/*** index.js ***/

//provide "alias" for value when importing!
import {foo as myFoo} from './my-module.js';
myFoo(); //=> 'foo'
foo(); //error, does not exist (aliased the variable as `myFoo`)

import { yourBar } from './my-module.js'; //import value by exported name
yourBar() //=> 'bar'

import { bar } from './my-module.js'; //error, no value `bar` exported
```

E' possibile `import`are _tutto_ cio' che e' stato exportato da un module usando la sintassi **`import * as`**. Specifichi un nome per l'object che rappresentera' i values exportati dal module (ad es. `theModule` nell'esempio sotto), e ogni variable exportata sara' una _property_ di quell'object. Questo puo' essere utile quando potresti aggiungere altri `exports` a un module durante lo sviluppo, ma non vuoi continuare a modificare l'`import` statement; d'altro canto, il resto del codice puo' essere piu' difficile da leggere perche' devi accedere alle properties dell'object.

```js
/*** index.js ***/
import * as theModule from './my-module'; //import everything that was exported
                                          //loads as a single object with values
                                          //as properties
theModule.foo(); //=> 'foo'
theModule.yourBar(); //=> 'bar'
theModule.baz(); //Error (private function so wasn't exported)
```

Infine, ogni module puo' anche `export`are una _singola_ (una sola!) variable **default**, che fornisce una scorciatoia quando importi quella variable dal module. Specifichi il _default export_ includendo la keyword **`default`** subito dopo `export`:

```js
/*** my-module.js ***/
//this function is the "default" export
export default function sayHello() {
    return 'Hello world!';
}
```

```js
/*** index.js ***/
import greet from './my-module'; //import the default value
                                 //`greet` is alias defined in this module

greet(); //=> "Hello world!"
```

Quando importi un `default` export, non includi `{}` con il nome della variable, ma fornisci invece un nome di variable ("alias") con cui vuoi riferirti a quel value exportato.

Nota che e' anche possibile rendere values anonimi `default` exports:

```js
/*** animals.js ***/
export default ['lion', 'tiger', 'bear']; //export anonymous array
```

La tecnica del `default` export e' particolarmente comune in framework object-oriented come React, o in framework grandi come Bootstrap con molti moduli indipendenti. Usare default exports ti permette di far si' che ogni module JavaScript contenga il codice per una singola function o `class`; quella function diventa il `default` export, permettendo ad altri moduli di importarla rapidamente e facilmente, ad es. `import MyComponent from './MyComponent.js'`.

Detto questo, in generale ti consiglio di usare _named imports_ nella maggior parte delle situazioni&mdash;c'e' meno sintassi da ricordare e riduce il numero di decisioni su cosa sia default o no. Devi conoscere i `default` exports perche' molte librerie di terze parti li usano, ma per il tuo lavoro e' spesso meglio restare sui named imports.


## Classes {#es6-classes}
<p class="alert alert-warning">Le classes non sono piu' comunemente usate in React e sono un po' sconsigliate in JavaScript. Questa sezione e' mantenuta per motivi storici e informativi, ma puo' essere considerata "deprecated" per questo corso.</p>

Anche se JavaScript e' principalmente un linguaggio _scripting_ e funzionale, supporta una forma di **Object Oriented Programming** simile a quella del linguaggio Java. Cioe', possiamo definire **classes** di data e metodi che agiscono su quei data, e poi **instantiate** quelle classi in **objects** che possono essere manipolati. ES6 introduce una nuova sintassi `class` per fare in modo che creare classi in JavaScript _sembri_ come creare classi in Java!

### Why Classes? {-}
Il punto di usare le classes in programmazione&mdash;sia in Java che in JavaScript&mdash;e' fare **abstraction**: vogliamo _encapsulate_ ("raggruppare") parti del codice in modo da poter ragionare a un livello piu' alto. Quindi, invece di pensare al programma solo in termini di `Numbers`, `Strings` e `Arrays`, possiamo pensarlo in termini di `Dogs`, `Cats` o `Persons`.

In particolare, le classes _encapsulate_ due cose:

1. I **data** (variables) che descrivono la cosa. Questi sono chiamati _attributes_, _fields_ o _instance variables_ (variables che appartengono a una specifica _instance_, ad esempio, della class). Per esempio, potremmo parlare di un object's `Person` con `name` (una String), `age` (un Number) e Halloween haul (un array di candy).

2. I **behaviors** (functions) che operano su, usano o cambiano quei data. Questi sono chiamati _methods_ (tecnicamente _instance methods_, perche' operano su una specifica instance della class). Per esempio, una `Person` potrebbe `sayHello()`, `trickOrTreat()` o `eatCandy()`.

In JavaScript, le properties di un Object possono essere viste come gli _attributes_ di quell'object. Per esempio:

```javascript
const person = {
   name: 'Ada',
   age: 21,
   costume: 'Cheshire Cat'
   trickOrTreat: function(newCandy){
      this.candy.push(newCandy);
   }
}

//tell me about this person!
console.log(person.name + " is a " + person.costume);
```

Questo Object rappresenta una cosa con attributes `name`, `age` e `costume` (ma non abbiamo ancora indicato che questo Object ha la *class*ification di "Person"). Il value della property `trickOrTreat()` e' una function (ricorda: le functions sono values!), ed e' un esempio di come un Object possa "avere" una function.

- JavaScript usa persino la keyword `this` per riferirsi a _quale_ object quella function viene chiamata, proprio come Java! Vedi [sotto](#working-with-this) per maggiori dettagli sulla keyword `this` e le sue particolarita'.

Una **Class** (*class*ification) agisce come
_template/recipe/blueprint_ per gli objects individuali. Definisce quali data (attributes) e behaviors (methods) hanno. Un object e' una "instance of" (esempio di) una class: noi **instantiate** un object a partire da una class. Questo ti permette di creare facilmente piu' objects, ognuno dei quali puo' tracciare e modificare i propri data. Le [ES6 classes](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes) forniscono una sintassi con cui definire questi "template".

<p class="alert alert-info">Lo styling preferito di React non si basa piu' molto sulla class syntax, ma e' comunque una buona idea avere familiarita' con essa per aiutare la comprensione e nel caso ti serva per lavori piu' complessi.</p>

### Review: Classes in Java {-}
Per prima cosa, considera la seguente class semplice definita in _Java_ (che dovrebbe essere un ripasso dai corsi di programmazione precedenti):

```java
//class declaration
public class Person {

    //attributes (private)
    private String firstName;
    private int age;

    //a Constructor method
    //this is called when the class is instantiated (with `new`)
    //and has the job of initializing the attributes
    public Person(String newName, int newAge){
        //assign parameters to the attributes
        this.firstName = newName;
        this.age = newAge;
    }

    //return this Person's name
    public String getName() {
        return this.firstName; //return own attribute
    }

    //grow a year
    public void haveBirthday() {
        this.age++; //increase this person's age (accessing own attribute)
    }

    //a method that takes in a Person type as a parameter
    public void sayHello(Person otherPerson) {
        //call method on parameter object for printing
        System.out.println("Hello, " + otherPerson.getName());

        //access own attribute for printing
        System.out.println("I am " + this.age +  " years old");
    }
}
```

Naturalmente puoi usare questa class (instantiarla e chiamarne i methods) in questo modo:

```java
public static void main(String[] args) {
    //instantiate two new People objects
    Person aliceObj = new Person("Alice", 21);
    Person bobObj = new Person("Bob", 42);

    //call method on Alice (changing her fields)
    aliceObj.haveBirthday();

    //call the method ON Alice, and PASS Bob as a param to it
    aliceObj.sayHello(bobObj);
}
```

Alcune cose da notare su questa sintassi:

1. Dichiari (annunci) che stai definendo una class usando la keyword `class`.
2. Gli attributes Java sono _dichiarati_ in cima al block della class (ma assegnati nel constructor).
3. Le classes hanno methods **constructor** usati per instanziare gli attributes.
4. I class methods sono dichiarati _dentro_ la dichiarazione della class (dentro il block, indentati di un livello).
5. I class methods possono accedere (usare) gli attribute variables dell'object riferendosi a `this.attributeName`.
6. Tu **instantiate** objects del tipo della class usando la keyword `new` e poi chiamando un metodo con il nome della class (ad es. `new Person()`). Quel metodo _e'_ il constructor, quindi riceve i parametri del constructor.
7. Chiami i methods sugli objects usando la **dot notation** (ad es. `object.methodName()`).
8. Gli objects instanziati sono solo variables, quindi possono essere passati ad altri methods.

### ES6 Class Syntax {-}
Ecco come creeresti _la stessa identica class_ in JavaScript usando la sintassi ES6:

```javascript
//class declaration
class Person {

    //a Constructor method
    //this is called when the class is instantiated (with `new`)
    //and has the job of initializing the attributes
    constructor(newName, newAge) {
        //assign parameters to the attributes
        this.firstName = newName;
        this.age = newAge;
    }

    //return this Person's name
    getName() {
        return this.firstName; //return own attribute
    }

    //grow a year
    haveBirthday() {
        this.age++; //increase this person's age (accessing own attribute)
    }

    //a method that takes in a Person type as a parameter
    sayHello(otherPerson) {
        //call method on parameter object for printing
        console.log("Hello, " + otherPerson.getName());

        //access own attribute for printing
        console.log("I am " + this.age +  " years old");
    }
}
```

Ed ecco come useresti questa class:

```javascript
//instantiate two new People objects
const aliceObj = new Person("Alice", 21);
const bobObj = new Person("Bob", 42);

//call method on Alice (changing her attributes)
aliceObj.haveBirthday();

//call the method ON Alice, and PASS Bob as a param to it
aliceObj.sayHello(bobObj);
```

Come puoi vedere, questa sintassi e' _molto, **molto**_ simile a Java! Proprio come per le functions JavaScript, la maggior parte dei cambiamenti riguarda l'eliminazione delle dichiarazioni di tipo. In effetti, puoi scrivere una class in Java e poi cancellare alcune parole per ottenere una class ES6.

Cose da notare:

1. _Proprio come in Java_, le classes JavaScript si dichiarano usando la keyword `class` (introdotta in ES6). <p class="alert">Dai sempre alle classes nomi in PascalCase (iniziando con una lettera maiuscola)!</p>

2. Le classes JavaScript **non** dichiarano gli attributes in anticipo (in cima alla class). A differenza di Java, le variables JavaScript esistono sempre, sono solo `undefined` finche' non vengono assegnate, quindi non serve dichiararle esplicitamente.

    - In JavaScript, niente e' private; hai di fatto accesso `public` a tutti gli attributes e functions.
3. Le classes JavaScript hanno sempre un solo **constructor** (se presente), e la function si chiama semplicemente `constructor()`.

    - Questo e' ancora piu' chiaro che in Java, dove sai che e' un constructor solo perche' manca un return type.
4. _Proprio come in Java_, i class methods JavaScript sono dichiarati _dentro_ la dichiarazione della class (dentro il block, indentati di un livello).

    Nota pero' che non serve usare la parola `function` per indicare che un method e' una function; basta fornire il nome e i parametri. Questo perche' le uniche cose _dentro_ una class sono functions, quindi dichiararlo sarebbe ridondante.

5. _Proprio come in Java_, i class methods JavaScript possono accedere (usare) le attribute variables dell'object riferendosi a `this.attributeName`.
6. _Proprio come in Java_, **instantiate** gli objects del tipo della class usando la keyword `new` e poi chiamando un method con il nome della class (ad es. `new Person()`). Quel method _e'_ il `constructor()`, quindi riceve i parametri del constructor.
7. _Proprio come in Java_, chiami i methods sugli objects usando la **dot notation** (ad es. `object.methodName()`).
8. _Proprio come in Java_, gli objects instanziati sono solo variables, quindi possono essere passati ad altri methods.

Quindi, in pratica, e' come Java&mdash;tranne per le differenze nel modo di dichiarare le functions e per il fatto che usiamo la parola `constructor` per i constructor methods.

L'altra differenza e' che mentre in Java di solito definiamo ogni class nel suo file, in JavaScript spesso crei piu' classi in un singolo file, allo stesso livello globale in cui dichiari anche le functions non-class:

```javascript
//script.js
'use strict';

//declare a class
class Dog {
    bark() { /*...*/ }
}

//declare another class
class Cat {
    meow() { /*...*/ }
}

//declare a (non-class) function
function petAnimal(animal) { /*...*/ }

//at the "main" level, instantiate the classes and call the functions
const fido = new Dog();
petAnimal(fido); //pass this Dog object to the function
```

<p class="alert alert-warning">Anche se la sintassi sopra sembra Java, e' importante ricordare che le instance di class JavaScript sono ancora _semplici Objects come gli altri_. Per esempio, puoi aggiungere nuove properties e functions a quell'object, o sovrascrivere il value di qualsiasi property. Anche se sembra una class Java, in realta' non si comporta come tale.</p>

### Inheritance {-}
La sintassi `class` di ES6 permette anche di specificare **class inheritance**, con cui una class puo' `extend`ere un'altra. L'inheritance ti permette di specificare che una class e' una _versione piu' specializzata_ di un'altra: cioe' una versione con "extra abilities" (come methods aggiuntivi).

Come in Java, usi la keyword `extends` per indicare che una class deve **inherit** da un'altra:

```js
//The "parent/super" class
class Dog {
  constructor(name) {
      this.name = name;
  }

  sit() {
      console.log('The dog '+this.name+' sits. Good boy.');
  }

  bark() {
      console.log('"Woof!"');
  }
}

//The "child/sub" class (inherits abilities from Dog)
class Husky extends Dog {
    constructor(name, distance) {
        super(name); //call parent constructor
        this.distance = distance;
    }

    //a new method ("special ability")
    throwFootball() {
        console.log('Husky '+this.name+' throws '+this.dist+' yards');
    }

    //override (replace) parent's method
    bark() {
      super.bark(); //call parent method
      console.log("(Go huskies!)");
    }
}

//usage
const dog = new Husky("Harry", 60); //make a Husky
dog.sit(); //call inherited method
dog.throwFootball(); //call own method
dog.bark(); //call own (overridden) method
```

In questo caso, la class `Husky` e' una _versione specializzata_ della class `Dog`: ___e' un___ `Dog` con alcune abilita' speciali (ad es. puo' lanciare un football). Ci riferiamo alla class base, meno specializzata (`Dog`), come **parent** o **super class**, e alla class derivata, piu' specializzata (`Husky`), come **child** o **sub-class**.

La sub-class `Husky` **inherits** i methods definiti nel parent: anche se la class `Husky` non ha definito un method `sit()`, lo ha comunque perche' il _parent_ lo ha definito! Estendendo una class esistente, ottieni molti methods gratis!

La class `Husky` puo' anche **override** i methods del parent, definendo una versione specializzata (ad es. `bark()`). Questo e' utile per aggiungere personalizzazione, o per fornire implementazioni specifiche di callback che possono essere usate da un framework&mdash;un pattern che vedrai in React.

<p class="alert alert-info">Nota che, nonostante questa discussione, _JavaScript non e' in realta' un linguaggio object-oriented_. JavaScript usa invece un [prototype system](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Objects/Object_prototypes) per definire tipi di Objects, che permette la cosiddetta [prototypical inheritance](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Objects/Inheritance). La keyword `class` di ES6 non cambia questo: e' semplicemente una "shortcut syntax" per specificare i prototype Objects nello stesso modo supportato fin dalla prima versione di JavaScript. La keyword `class` rende facile definire qualcosa che sembra e si comporta come una OOP class, ma JavaScript non e' object-oriented! Vedi [questa spiegazione (dettagliata)](http://aaditmshah.github.io/why-prototypal-inheritance-matters/) per ulteriori dettagli.</p>


### Working with <code>this</code> {-}

In JavaScript, le functions sono chiamate su **Objects** usando la _dot notation_ (ad es. `myObject.myFunction()`). Dentro una function, puoi riferirti all'Object su cui e' stata chiamata usando la keyword **`this`**. `this` e' una variable locale che viene _implicitamente assegnata_ all'Object come value.

```js
const doggy = {
  name: "Fido",
  bark: function() {
      console.log(this.name, "woofs"); //`this` is object the function was called on
  }
}

doggy.bark(); //=> "Fido woofs"
```

- Qui `this` e' assegnato all'object `doggy`, su cui e' stato chiamato `.bark()`.

Ma dato che le functions sono values e possono essere assegnate a piu' variables (con etichette diverse), l'object su cui una function viene chiamata non e' necessariamente l'object a cui era stata assegnata inizialmente come property. `this` si riferisce all'object su cui la function e' chiamata al momento dell'esecuzione, non al momento della definizione:

```js
//An object representing a Dog
const doggy = {
  name: "Fido",
  bark: function() { console.log(this.name + " woofs"); }
}

// An object representing another Dog
const doggo = {
  name: "Spot",
  bark: function() { console.log(this.name + " yips")}
}

//This is Fido barking
doggy.bark( /*this = doggy*/ ); //=> "Fido woofs"

//This is Spot barking
doggo.bark( /*this = doggo*/ ); //=> "Spot yips"

//This is Fido using Spot's bark!
doggy.bark = doggo.bark; //assign the function value to `doggy`
doggy.bark( /*this = doggy*/) //=> "Fido yips"
```

- Nota come la variable `this` viene implicitamente assegnata al value dell'object su cui e' stata chiamata&mdash;anche se la function viene assegnata a un nuovo object in seguito!

Ma dato che la variable `this` si riferisce all'object su cui la function e' chiamata, possono sorgere problemi per le _anonymous callback functions_ che non sono chiamate su un object in particolare:

```js
class Person {
   constructor(name){ this.name = name; } //basic constructor

   //greet each person in the given array
   greetAll(peopleArray) {
      //loop through each Person using a callback
      peopleArray.forEach(function(person) {
         console.log("Hi"+person.name+", I'm "+this.name);
      });
   }
}
```

In questo esempio, la function `greetAll()` produrra' un errore: `TypeError: Cannot read property 'name' of undefined`. Questo perche' `this` viene usato dentro una anonymous callback function (la `function(person){...}`)&mdash;e quella callback non viene chiamata su un object specifico (nota l'assenza di dot notation). Dato che la callback anonima non viene eseguita su un object, `this` viene assegnato al value `undefined` (e non puoi accedere a `undefined.name`).

La soluzione a questo problema e' usare le _arrow functions_. Una arrow function ha la feature speciale di condividere lo stesso `this` lessicale del codice circostante: cioe', `this` non viene riassegnato a un object (inesistente) quando usato dentro una arrow function:

```js
class Person {
   constructor(name){ this.name = name; }

   greetAll(peopleArray) {
      peopleArray.forEach((person) => { //arrow function (subtle difference)
         console.log("Hi"+person.name+", I'm "+this.name); //works correctly!
      });
   }
}
```

Questa proprieta' rende le arrow functions preziose quando specifichi callback functions, soprattutto quando entrano in gioco classes e objects. _Usa sempre arrow functions per le anonymous callbacks!_

<div class="alert alert-info">In alternativa, e' possibile associare "permanentemente" un particolare value di `this` a una function, indipendentemente dall'object su cui quella function viene chiamata. Questo si chiama **binding** di `this`, e si fa chiamando il metodo [`.bind()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/bind) sulla function e passando il value che vuoi assegnare a `this`. Il metodo `.bind()` restituisce una _nuova function_ che ha il value associato; spesso poi prendi questa nuova function e la "re-assign" alla vecchia variable della function:

```js
//re-assign function
myFunction = myFunction.bind(thisValue);
```

Questo e' un pattern comune in React (e ha alcuni minimi benefici di performance), ma per questo corso dovresti restare sulle arrow functions per pulizia e leggibilita'.</div>


Questo capitolo ha descritto alcune delle feature ES6 piu' comuni e potenzialmente utili. Tuttavia, ricorda che la maggior parte di queste sono solo "syntactic shortcuts" per behavior e funzionalita' che puoi gia' ottenere usando JavaScript in stile ES5. Quindi non devi per forza usare queste feature nel tuo codice&mdash;anche se possono essere utili e compariranno spesso nel modo in cui usiamo librerie come React.


<!-- ## Resources {-}
<div class="list-condensed">
- [ES6 For Humans](https://github.com/metagrover/ES6-for-humans) an good online text on ES6
- [ECMAScript 6](https://github.com/lukehoban/es6features#readme) A good unofficial summary with examples
- [ES6 Features](http://es6-features.org/) (also shows equivalent ES5 syntax where possible)
- [ECMAScript 2015 Language Specification](http://www.ecma-international.org/ecma-262/6.0/) official standard
</div> -->
