# Librerie JavaScript
Molti web programmer incontrano gli stessi requisiti di programmazione mentre sviluppano web sites interattivi. Per esempio, molti siti devono gestire e manipolare objects e arrays, mostrare componenti standard (come modal windows o contenuti collapsible) o fare forme simili di complessa DOM manipulation. Poiche' uno dei principi principali dello sviluppo software e' il [___reuse___](https://en.wikipedia.org/wiki/Reusability), i developer spesso rendono disponibile ad altri il codice che risolve questi problemi sotto forma di **libraries e frameworks**. Sono file script rilasciati pubblicamente che puoi scaricare e includere nel tuo project, permettendoti di sviluppare applicazioni complesse piu' rapidamente e facilmente. Questa e' la cosa fantastica della comunita' open-source: le persone risolvono problemi e poi rendono quelle soluzioni disponibili agli altri.

Le web applications moderne fanno un uso _esteso_ di librerie esterne, sia integrando molte librerie diverse in una sola app, sia facendo affidamento su un framework specifico (che puo' a sua volta essere composto da molte librerie diverse)! Questo capitolo descrive come includere e utilizzare librerie JavaScript esterne nella tua web page, e presenta la popolare libreria [jQuery](https://jquery.com/) come esempio.

- Per un'idea di scala, la directory del package manager [**npm**](https://www.npmjs.com/) elenca quasi _mezzo milione_ di librerie JavaScript diverse!

Nota che gli script esterni sono in genere chiamati _libraries_ o _frameworks_. Tuttavia, questi termini non sono completamente intercambiabili. Una **library** e' un insieme di behaviors (functions) che puoi usare e chiamare nel tuo codice. Per esempio, `Lodash` (descritto sotto) e' una library che fornisce utility functions utilizzabili. Chiami il codice della library quando vuoi. Un **framework**, invece, fornisce un insieme di codice in cui inserisci i tuoi _behaviors_, per esempio subclassando componenti forniti o specificando le tue callback functions. Il framework chiama _il tuo_ codice quando vuole lui. [Martin Fowler](http://martinfowler.com/bliki/InversionOfControl.html) si riferisce a questo come _"Inversion of control"_. I framework spesso sembrano piu' facili da usare (fanno di piu' con meno lavoro da parte tua!), ma possono essere difficili da personalizzare per raggiungere obiettivi precisi. Le libraries possono essere piu' difficili da usare, ma probabilmente puoi impiegarle esattamente come serve. Questo capitolo si concentra principalmente sulle _libraries_; [React](https://reactjs.org/) (descritto nei capitoli successivi) e' piu' un framework.


## Includere una Library
Proprio come puoi includere piu' file CSS in una pagina con elementi `<link>` multipli, puoi includere piu' script JavaScript con elementi `<script>` multipli.

```html
<script src="alpha.js"></script> <!-- esegui questo script per primo -->
<script src="beta.js"></script> <!-- esegui questo script per secondo -->
```

_Importante_, i file script vengono eseguiti nell'ordine in cui appaiono nel DOM. Questo conta perche' tutti gli script inclusi tramite l'elemento `<script>` vengono eseguiti nello stesso [namespace](https://en.wikipedia.org/wiki/Namespace). Questo significa che variables e functions dichiarate in uno script sono disponibili negli script successivi&mdash;e' quasi come se tutti i file script fossero combinati in un unico file.

```js
/* alpha.js */
let message = "Ciao Mondo";
```

```js
/* beta.js */
console.log(message); //=> "Ciao Mondo"
                      //la variable era definita nello script precedente!
```

L'ordine conta: se `beta.js` fosse incluso _prima_ di `alpha.js`, quando viene eseguito la variable `message` non sarebbe ancora definita, causando un errore.

<p class="alert alert-info">Altre tecniche per gestire e organizzare grandi numeri di file script saranno discusse nel [Chapter 15](#es6).</p>

Come per i CSS frameworks, le JavaScript libraries si includono in una pagina fornendo un tag `<script>` che referenzia il file JavaScript che contiene il codice della library. Per esempio, puoi includere [Lodash](https://lodash.com/) con utili funzioni di data processing:

```html
<body>
    ...content

    <!-- include JavaScript files -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/lodash.js/4.17.4/lodash.min.js"></script>
    <script src="js/my-script.js"></script>
</body>
```

- Come per i CSS frameworks, le JavaScript libraries possono essere usate referenziando il file su un **CDN**, scaricando direttamente il source code (cerca il file `.js`; potresti dover estrarre un file `.zip`), oppure installando la library tramite un package manager come `npm`. Vedi il [Chapter 3](#including-a-framework) per i dettagli&mdash;basta sostituire `.css` con `.js`!


- Come per il CSS, i file JavaScript possono essere _minimized_ (di solito chiamati `.min.js`). Minimizzare i file JavaScript non solo rimuove il whitespace, ma spesso sostituisce anche i nomi delle variables locali con nomi piu' corti e senza significato come `a` o `x`.

Vuoi **sempre** caricare le libraries esterne prima del tuo script, cosi' le variables e functions che definiscono saranno disponibili al tuo codice! Se metti prima il tuo script, quelle functions non saranno ancora disponibili!

Dato che tutti i file JavaScript condividono lo stesso namespace, la maggior parte delle libraries popolari rende tutte le sue functions disponibili come properties di una singola **global variable**. Per esempio, Lodash fornisce una global variable chiamata **`_`** (un singolo underscore&mdash;un "low dash"). Usi questa variable per chiamare le functions fornite:

```js
let array = [3,4,3];

let unique = _.uniq(array); //chiama una function dell'object lodash

console.log(unique); //[3,4], gli elementi unici!
```

- Una volta caricata la library, i globals che fornisce possono essere accessi come i built-in globals `window`, `document`, `Math`, ecc.

- Lodash usa un nome di variable apparentemente strano per essere rapido e facile da digitare, e per evitare conflitti con altre variables che potresti creare.

Lodash fornisce [molte funzioni utili](https://lodash.com/docs/) che possono essere chiamate sull'object globale `_`. Per esempio:

<div class="list-condensed">
- [`_.random()`](https://lodash.com/docs/4.17.4#random) per generare un numero casuale in un intervallo
- [`_.range()`](https://lodash.com/docs/4.17.4#range) per generare un array di numeri in un intervallo
- [`_.includes()`](https://lodash.com/docs/4.17.4#includes) per determinare se un value e' in un array (cross-browser!)
- [`_.pick()`](https://lodash.com/docs/4.17.4#pick) per produrre un nuovo object che ha solo alcune properties di un altro
- [`_.merge()`](https://lodash.com/docs/4.17.4#merge) per combinare le properties di due objects in un singolo nuovo object
</div>

Nota che quale object globale viene fornito (e quali functions ha) e' diverso per ogni library. Devi guardare la documentazione (spesso il file `README.md` su Github) per istruzioni ed esempi su come chiamare e utilizzare quella library.

- "Conoscere" una library o framework significa solo essere familiari con le functions che puoi chiamare!

<p class="alert alert-info">**Pro-tip**: Visual Studio Code [scarichera' automaticamente le type definitions](https://code.visualstudio.com/docs/editor/intellisense) per qualsiasi library elencata come dependency nel `package.json` del progetto. Per esempio, se includi Lodash come dependency (installandola con `npm install --save lodash`), allora digitando `_.` VS Code mostrera' opzioni di autocomplete. Questo rende una buona idea installare le JavaScript libraries via `npm`, anche se poi pianifichi di caricare la library da un CDN invece che da un file locale.</p>

<p class="alert alert-info">Se stai usando un linter per controllare il coding style, devi far sapere al linter di qualsiasi global variable caricata in altri script cosi' il linter non pensi che quelle variables siano undefined. Vedi [la documentazione](https://eslint.org/docs/user-guide/configuring#specifying-globals) per dettagli su come farlo in ESLint.</p>


## Esempio: jQuery
Come esempio esteso di una library JavaScript, il resto di questo capitolo descrive [**jQuery**](https://jquery.com/) -- una popolare library JavaScript che aiuta con la DOM manipulation. jQuery e' stata progettata per fornire metodi piu' facili, veloci e affidabili per manipolare il DOM nei modi descritti nel capitolo precedente. jQuery e' una delle librerie piu' popolari nel web development ed e' usata da circa il [70% dei siti piu' popolari](https://trends.builtwith.com/javascript/jQuery).

jQuery e' stata sviluppata per colmare lacune del linguaggio JavaScript e per standardizzare funzionalita' tra browser. Ha reso possibile manipolare il DOM scrivendo una frazione del codice, e produrre script che funzionavano sia su Firefox _sia_ su Internet Explorer.

Tuttavia, nei 10+ anni dalla sua uscita, il linguaggio JavaScript e le API DOM sono migliorati (ad es. con `querySelector()`), cosi' gran parte di cio' che rendeva speciale jQuery e' [ora standard e ampiamente supportato](http://youmightnotneedjquery.com/). In effetti, l'approccio di jQuery alle pagine interattive e' diventato pratica comune. Ciononostante, jQuery e' ancora usata in molti sistemi web ([i componenti JavaScript di Bootstrap](http://getbootstrap.com/docs/4.0/getting-started/javascript/) la usano) ed e' abbastanza diffusa da rendere utile conoscerla, soprattutto se devi lavorare su un sistema costruito piu' di 3 anni fa.

Come per altre librerie, [includi jQuery](https://jquery.com/download/) referenziandola con un tag `<script>` nel tuo HTML (_prima del tuo script!_):

```html
<script src="http://code.jquery.com/jquery-3.2.1.min.js"></script>
```

- Nota che la versione jQuery `3.x` e' per i [browser attuali](https://jquery.com/browser-support/). Se devi supportare versioni piu' vecchie (ad es. IE 6-8), puoi usare la `1.12`. Si', jQuery supporta IE 6!

Caricare la library jQuery crea una variable **`jQuery`** nello scope globale, quindi puoi accedervi e usarla nello script.

La variable `jQuery` e' in realta' una _function_ che puoi chiamare, detta **Selector function**. Questa function seleziona elementi DOM tramite [CSS selector](http://api.jquery.com/category/selectors/basic-css-selectors/), simile a `document.querySelector()`:

```js
//seleziona l'elemento con id="foo" (es. <p id="foo">)
let fooElem = jQuery('#foo');

//seleziona tutti gli elementi <a>
let allLinksArray = jQuery('a');
```

Tuttavia, e' molto piu' comune usare un _alias_ fornito per `jQuery()`, chiamato **`$()`**. Questa scorciatoia permette di selezionare elementi con un solo carattere (invece di 6).

```js
//seleziona l'elemento con id="foo" (es. <p id="foo">)
let fooElem = $('#foo');

//seleziona tutti gli elementi <a>
let allLinksArray = $('a');
```

- Come per `_` in Lodash, jQuery usa `$` perche' nessuno sano di mente darebbe quel nome a una variable, quindi la probabilita' di conflitti di namespace e' minima.

Come `document.querySelector()`, la function selector di jQuery gestisce la maggior parte dei [selector](http://api.jquery.com/category/selectors/) CSS, oltre a qualche pseudo-class utile:

```js
$('#my-div') // per id
$('div') // per tipo
$('.my-class') // per class
$('header, footer') // selector di gruppo
$('nav a') // selector discendente
$('p.red') // selector con scope

$('section:first') // primo elemento <section>
                   // (non e' un css selector!)
```

### Manipolare il DOM {-}
Una volta selezionati gli elementi, jQuery fornisce _methods_ che eseguono la maggior parte delle [manipolazioni](http://api.jquery.com/category/attributes/) che faresti con le property del DOM:

```js
var txt = $('#my-div').text();      //ottieni il textContent
$('#my-div').text('new info!');     //cambia il textContent

$('#my-div').html('<em>new html!</em>'); //cambia l'HTML

$('svg rect').attr('height');       //ottieni l'attribute (di tutti i selezionati)
$('svg rect').attr('height',200);   //imposta l'attribute (di tutti i selezionati)
$('svg rect').attr( {x:50, y:60} ); //imposta piu' attributes passando un object

$('section').addClass('container'); //aggiungi class (a tutti i selezionati)
$('section').removeClass('old');    //rimuovi class (da tutti i selezionati)

$('body').css('font-size','24px');  //imposta la property CSS (di tutti i selezionati)
$('body').css( {'font-size':'24px',
                'font-family':'Helvetica'} ); //imposta piu' properties via un object
```

Se confronti questo con le operazioni equivalenti usando il DOM, noterai che (a) jQuery e' molto piu' conciso. jQuery e' anche piu' potente: per esempio, puoi impostare piu' attributes con una singola chiamata a `.attr()` passando un _object_ che contiene gli attributes da impostare (le keys sono i nomi degli attribute). Questo ti permette di cambiare facilmente molti attributes in una volta!

<p class="alert alert-warning">Importante: nota che tutti questi metodi applicano il cambiamento a ___tutti___ gli elementi selezionati dalla funzione selector di jQuery. Non devi usare un loop per applicare cambiamenti a piu' elementi; puoi semplicemente selezionare gli elementi che vuoi modificare e cambiarli tutti insieme. Questo significa che devi fare attenzione al selector&mdash;seleziona solo gli elementi su cui vuoi davvero lavorare!</p>

jQuery fornisce anche metodi che permettono di [manipolare](https://api.jquery.com/category/manipulation/) il DOM tree (ad es. per aggiungere, spostare o rimuovere elementi):

```js
//crea un elemento (non ancora nel DOM)
let newP = $('<p class="new">Questo e' un nuovo elemento</p>'); //nota il tag!

//aggiungi contenuto al DOM
$('main').append(newP); //aggiungi l'elemento DENTRO <main>, in fondo
$('main').append('<em>nuovo</em>'); //puoi creare un elemento al volo!

$('main').prepend('<em>nuovo</em>'); //aggiungi un nuovo elemento <em> DENTRO <main>, all'inizio

$('main').before('<header>'); //inserisci un nuovo <header> PRIMA di <main> (fratello precedente)
                              //nota che puoi omettere il tag di chiusura se non c'e' contenuto

$('footer').insertAfter('main'); //inserisci il selezionato (<footer>) DOPO il parametro (<main>)
                                 //dato che <footer> era selezionato, si spostera'!

$('main').wrap('<div class="container"></div>'); //circonda <main> con una .container

$('footer').remove(); //rimuove l'elemento <footer> selezionato
$('main').empty(); //rimuove tutti gli elementi child di <main>
```

La prima cosa importante da notare e' che crei nuovi elementi passando il contenuto HTML (incluso il tag `<>`) alla function `$()`. Questo e' diverso da `document.createElement()`, che esplicitamente _non_ include le parentesi angolari `<>`. Se crei un elemento senza contenuto, puoi anche specificare solo il tag di apertura!

jQuery offre anche metodi di manipolazione piu' potenti, permettendoti di posizionare elementi facilmente [inside](http://api.jquery.com/category/manipulation/dom-insertion-inside/), [outside](http://api.jquery.com/category/manipulation/dom-insertion-outside/), [around](http://api.jquery.com/category/manipulation/dom-insertion-around/) e [in place of](http://api.jquery.com/category/manipulation/dom-replacement/) altri elementi.

<p class="alert alert-warning">Anche se jQuery ti permette di creare elementi HTML arbitrariamente complessi da aggiungere al DOM, dovresti **evitare** di scrivere grandi blocchi di HTML dentro il file `.js` da appendere via jQuery (ad es. non aggiungere un intero DOM tree in una volta!). Questo viola la separation of concerns e rende il codice difficile da leggere, interpretare e modificare (perche' ora l'HTML e' in due posti!). Se devi inserire dinamicamente grandi quantita' di HTML "hard-coded", scrivi invece quel contenuto nel file `.html`, rendilo invisibile (ad es. `display:none`), e poi usa jQuery per spostare e mostrare l'elemento quando serve.</p>


### Gestire gli eventi {-}
jQuery fornisce anche _convenience methods_ per registrare event listener:

```js
$('#button').click(function(event) {
   console.log('clic clic!');

   //chi e' stato cliccato
   let element = $(event.target);
});
```

- Esistono metodi equivalenti per altri eventi: `.mousedown()`, `.keypress()`, ecc. Se vuoi ascoltare un event per cui jQuery non fornisce un convenience method, puoi usare la function `.on()`:

    ```js
    $('#search-input').on('input', callback);
    ```

Usando un metodo come `.click(callback)` invece di `.addEventListener('click', callback)` o `.on('click', callback)`, eviti bug difficili da catturare dovuti a typo di `'click'`&mdash;invece di far ascoltare al browser eventi `'clik'` e non vedere mai risposta alle tue azioni, verra' riportato un errore (`.clik()` non e' una function conosciuta!).

Il parametro [`event`](http://api.jquery.com/category/events/event-object/) passato alla callback di `.click()` e' esattamente come l'`event` passato alle callback di `addEventListener()` (anche se jQuery standardizza le differenze cross-browser)&mdash;quindi puoi accedere alla sorgente dell'event con la property `event.target`. Tuttavia, questa property si riferisce a un elemento DOM, _non_ a un selector jQuery. Gli elementi DOM non supportano i metodi jQuery descritti sopra&mdash;quelli sono disponibili solo sugli "jQuery selection objects". Quindi se vuoi lavorare con un elemento DOM, devi "selezionarlo" di nuovo usando la function `$()`, ottenendo una jQuery selection che ha tutti i metodi utili.

- Inoltre, jQuery assegna la variable `this` dentro una event callback al target dell'event; quindi puoi usare `$(this)` per selezionare l'elemento.

Il capitolo precedente ha citato l'event listener `window.onload`, usato per determinare quando il DOM ha finito di caricarsi ed e' pronto per essere manipolato. jQuery fornisce una funzionalita' simile tramite il listener `.ready()` (di solito chiamato su tutto il `document`):

```js
$(document).ready(function() { //non serve che sia una function anonima
    //il programma va qui
    console.log('Ciao mondo!');

    //...
});
```

Questo e' un pattern molto comune: spesso con jQuery interi programmi sono scritti dentro la callback `.ready()`, cosi' i tag `<script>` possono stare nel `<head>` ed essere scaricati rapidamente ma eseguiti solo quando il DOM e' disponibile. Questo pattern e' _cosi'_ comune che la function selector di jQuery puo' essere usata come scorciatoia:

```js
//equivalente a quello sopra
$(function() {
    //il programma va qui
    console.log('Ciao mondo!');

    //...
});
```
- Se passi una _function_ invece di una string Selector alla function jQuery `$()`, verra' interpretata come callback da eseguire quando il document e' pronto! Tienilo presente se guardi codice altrui e vedi che inizia con un `$(function)` a caso.

### E altro! {-}
Questo e' solo la punta dell'iceberg di cio' che jQuery puo' fare. Per esempio, jQuery fornisce anche diverse [utility](http://api.jquery.com/category/utilities/) function che possono essere chiamate sul global `jQuery` (o `$`):

```js
//controlla se un item e' in un array
$.inArray(4, [3,4,3] );
jQuery.inArray(4, [3,4,3] ); //equivalente, ma forse piu' leggibile

//trova un item in un array che matcha la function di filtro
//questo e' come .filter, ma funziona su browser vecchi (con la versione jQuery giusta)
$.grep( [3,4,3], function(item) {
   return item > 3;
});

//itera su arrays o objects -- funziona per entrambi!
$.each( [3,4,3], function(key, value) {
   console.log('Dammi un '+value);
});

$.each( {first:'Joel',last:'Ross'}, function(key, value) {
   console.log(key+' nome: '+value);
});
```

- Questo puo' essere utile, ma le functions native di JavaScript o i metodi Lodash saranno spesso piu' semplici e (computationally) piu' veloci.

E come ultimo esempio divertente: jQuery fornisce anche functions che permettono di creare facilmente [animated effects](http://api.jquery.com/category/effects/)!

```js
$('#id').fadeIn(1000);   //fade in in 1 secondo
$('#id').fadeOut(500);   //fade out in 1/2 sec
$('#id').slideDown(200); //slide down in 200ms
$('#id').slideUp(500);   //slide up in 500ms
$('#id').toggle();       //toggle se visualizzato

//sintassi di animazione custom:
//$(selector).animate({targetProperties}, speed [, doneCallback]);
$("#box").animate({
    left: '500px', //fai volare la box in giro!
    opacity: '0.5',
    height: '200px',
    width: '200px'
}, 1500);
```

<!-- ## Esempio: Bootstrap
//altro esempio: JS di Bootstrap
//esempio: collapse? -->

## Risorse {-}
<div class="list-condensed">
- [Lodash Documentation](https://lodash.com/docs/)
- [jQuery Documentation](http://api.jquery.com/)
- [jQuery Learning Center](https://learn.jquery.com/)
- [jQuery Tutorial (w3c)](https://www.w3schools.com/jquery/)
</div>
