# Strumenti React

React e altri approcci moderni di sviluppo JavaScript richiedono di sfruttare una varieta' di libraries esterne, e spesso richiedono altri passi di compilazione come il **transpiling** a ES6, o il **bundling** del tuo JavaScript in un singolo file. Esistono diversi tools disponibili per rendere questi passi piu' facili, alcuni dei quali introdurremo qui.


## Importare ed Esportare in ES6
Una delle feature piu' potenti di ES6 e' la possibilita' di importare ed esportare functions dai file. Questo ti permette di creare blocchi di codice riusabili che sono facilmente integrabili in piu' progetti. Non devi piu' considerare se un file JavaScript diverso e' stato caricato nel file `index.html`. Invece, possiamo importare le functions desiderate direttamente nei nostri script. Inoltre, significa che non devi includere un'intera library -- puoi importare solo le functions che vuoi, e lasciare fuori il resto. Questo aiuta a prevenire collisioni di namespace e a limitare la dimensione dei file del tuo progetto.

Questo [articolo](http://wesbos.com/javascript-modules/) fornisce una definizione operativa di _JavaScript Modules_:

>I JavaScript modules ci permettono di spezzare il nostro codice in file separati dentro il nostro project o di usare moduli open source che possiamo installare tramite npm. Scrivere il tuo codice in moduli aiuta con l'organizzazione, la manutenzione, i test e, soprattutto, la gestione delle dependencies.

Inizieremo scrivendo una function semplice che possiamo _exportare_ -- questo rendera' le functions disponibili ad altri script che le _importano_:

```javascript
// Nel nostro file utility.js, scrivi una function che converte feet in meters
function feetToMeters(feet) {
    return feet / 3.28084
}

// Scrivi un'altra function metersToFeet
function metersToFeet(meters) {
    return meters * 3.28084
}

// Esporta ogni function nominata
export {feetToMeters, metersToFeet} // named exports

```

Se poi vogliamo usare `feetToMeters` in un'altra function, possiamo semplicemente importarla:

```javascript
// Nel nostro file main.js, importa la function feetToMeters
import {feetToMeters} from './utility' // assumendo che siamo nella stessa directory

```

### Named vs. default exports
L'esempio sopra dimostra l'uso di _named_ exports, in cui nominiamo esplicitamente ogni object che vogliamo esportare, e poi lo nominiamo esplicitamente per importarlo.


```javascript
// Utility.js ----------
// Scrivi una function che converte feet in meters
// Nel nostro file utility.js, scrivi una function che converte feet in meters
function feetToMeters(feet) {
    return feet / 3.28084
}

// Esporta ogni function nominata
export {feetToMeters} // named exports

```

Ci sono poi tre opzioni di sintassi per _importare_ i **named exports**:

```javascript
// Opzioni di importazione per un named export (vedi sopra)

// Opzione 1 -------- importa named exports per nome
import {feetToMeters, metersToFeet} from './Utility';
let meters = feetToMeters(30); // usa la function


// Opzione 2 -------- importa named exports per nome CON un nome piu' corto
import feetToMeters as f2m from './Utility'
let meters = f2m(30); // usa la function


// Opzione 3 -------- importa tutti i named exports con un prefisso
// Importa i nostri components
import * as Utilities from './Utility';
let meters = Utilities.feetToMeters(30); // usa la function
```

In alternativa, puoi esportare un **single default object** da un modulo:


```javascript
// Utility.js ----------
// Nel nostro file utility.js, scrivi una function che converte feet in meters
function feetToMeters(feet) {
    return feet / 3.28084
}

// Esporta un modulo di default
export default feetToMeters; // single default export

```

Poi, per importare la **default export**, puoi usare la seguente sintassi:

```javascript
import feetToMeters from './Utility.js'
```

Userai questa sintassi per importare // esportare le tue functions, e la userai anche per importare functions da **libraries esterne**.

## Installare con NPM

Abbiamo introdotto l'uso di NPM in un [capitolo precedente](machine-setup.html#node-and-npm), principalmente per installare packages che erano descritti nel file `package.json`. Man mano che procediamo, useremo NPM per **installare packages aggiuntivi** e **deployare il nostro codice**.

E' comune che, a meta' di un progetto, tu identifichi **libraries aggiuntive** che vuoi usare nel tuo progetto. Puoi usare NPM per installare un package e **aggiungerlo alla tua lista di packages** se usi l'opzione `--save`:

```bash
# Scarica la library lodash e aggiungila alla tua lista di packages
npm install lodash --save  # make sure to run this in your project folder
```

Aggiungerlo alla tua lista di packages permette ad altri di installare i file necessari per usare il tuo programma. Quando inizi a usare un programma di compilazione (come la funzionalita' integrata in `create-react-app`) potrai importare funzionalita' dalla tua cartella `node_modules` come faresti con altre functions (cioe', `import `):

```javascript
// In un file JS in un progetto che viene compilato (usando create-react-app)
import {uniq} from 'lodash';   // import a named export
let vals = uniq([1, 2, 3, 1]); // restituisce [1, 2, 3]
```


## Create-React-App
Per sfruttare una struttura piu' complessa per il nostro codice (come importare ed esportare functions), dobbiamo **compilare il nostro JavaScript** prima di caricarlo nel browser. Ci sono vari tools che le persone usano per farlo, come [Gulp](http://gulpjs.com/), [Browserify](http://browserify.org/) e [Webpack](https://webpack.github.io/). Questi tools sono ottimi per configurare un build system per il tuo progetto, ma possono richiedere tempo per essere configurati (soprattutto se non hai specifiche custom che stai cercando di ottenere).

Quindi, le persone di React hanno costruito un tool fantastico chiamato [create-react-app](https://github.com/facebookincubator/create-react-app), che combina piu' tools (incluso Webpack) per compilare il tuo codice per te. E' super facile iniziare:


```bash
# Installa globalmente l'utility da command line create-react-app: fallo solo una volta!
# A seconda dei permessi sulla tua macchina, potresti dover usare `sudo npm install....`
npm install -g create-react-app

# Crea un project chiamato my-app (un child della tua directory corrente)
create-react-app my-app

# Cambia la tua directory in my-app
cd my-app/

# Avvia un server locale con il tuo project: visibile su localhost:3000
npm start  # this functionality is defined in the package.json file that was created
```

Create React App e' un po' opinionated sulla struttura del tuo codice, ma offre diversi vantaggi. Per esempio, mostrera' **errors e warnings nella finestra del tuo browser**, **ricarichera' automaticamente** quando il tuo JavaScript cambia, e **iniettera' cambiamenti CSS** senza ricaricare la tua pagina. Quando crei un nuovo project, verranno creati i seguenti file:


```bash
my-app/
  README.md
  node_modules/
  package.json
  .gitignore
  public/
    favicon.ico
    index.html
  src/
    App.css
    App.js
    App.test.js
    index.css
    index.js
    logo.svg
```

Da li', puoi iniziare a modificare il tuo file `App.js`. Il tuo component `<App/>` viene renderizzato nella pagina, quindi dovresti estenderlo come preferisci. Ora puoi importare functions direttamente in un file JavaScript da libraries **o** dai tuoi moduli:

```javascript
// Importa i file desiderati
import {Component} from 'react' // import the Component class from the react library
import {uniq} from 'lodash';    // import a named export from the lodash library

// Crea una class App estendendo Component
class App extends Component {
  render() {
    return <div>My App</div>
  }
}

// Esporta il component App per importarlo in altri file
export default App;
```

### Building
Per fare il build della tua app per il deployment, userai il comando `npm run build` (puoi vedere che function esegue guardando il file `package.json`). Questo compilera' correttamente i tuoi file (inclusi JavaScript, CSS, immagini, ecc.) in un formato ottimizzato. L'unica cosa complicata e' che se stai cercando di ospitare il tuo build in una location specifica, dovrai **specificare quella location** nel tuo file `package.json`. Per esempio, immagina che tu stia ospitando il tuo sito su `http://students.washington.edu/YOUR-NAME/info-340/project-name`. Create React App assume che ospiterai il tuo progetto nella **root del tuo server**. In altre parole, quando fa il build, costruira' path relativi che assumono che le risorse siano nella root. Per adattare questo, dovrai modificare il tuo file `package.json`:

```javascript
{
  "name": "project-name",
  "version": "0.1.0",
  "private": true,
  "homepage": "http://students.washington.edu/YOUR-NAME/info-340/project-name",
  .....
}

```

Impostando `homepage`, i path relativi verranno costruiti correttamente. Questo creera' per te una cartella chiamata `build/`, in cui avrai i file necessari. Puoi poi **spostare questi file su di una directory** (cioe', fuori dalla cartella `build/`) se stai usando il tuo repo GitHub per l'hosting (questo e' un passaggio manuale sfortunato). Poi dovresti essere pronto per deployare!

Un'altra opzione e' usare la library `gh-pages`. Questo ti fornira' un tool da command line per creare un branch `gh-pages`, e spostare i file nella tua cartella `build/` su di una directory (il che significa che non devi andare all'URL `project-nanme/build/`). Ecco i passi per usare il package `gh-pages`:

```bash
# Installa il package gh-pages nel tuo progetto
npm install gh-pages --save
```

Poi, modifica il tuo file `package.json` per **aggiungere un nuovo comando** nella sezione `scripts`. Aggiungerai la linea di codice `"deploy"`.

```json
"scripts": {
     "start": "react-scripts start",
     "build": "react-scripts build",
     "test": "react-scripts test --env=jsdom",
     "eject": "react-scripts eject",
     "deploy": "npm run build&&gh-pages -d build"
 }
```

Poi, per deployare un progetto nel _branch_ `gh-pages` su GitHub, puoi semplicemente eseguire questa riga di codice (questa fara' il `build` del tuo progetto e fara' `commit` e `push` del progetto buildato nel tuo branch):

```bash
npm run deploy
```

Poi, sul tuo server, dovresti scaricare il codice e fare checkout del tuo branch `gh-pages`:

```bash
# Sul tuo server, come un server studenti UW
git clone PROJECT-URL
git checkout gh-pages

# Per aggiornare:
git pull origin gh-pages
```

## Risorse

- [React Create App](https://github.com/facebookincubator/create-react-app)
- [Documentazione Export](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/export)
- [Documentazione Import](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import)
- [Getting Started con WebPack](https://webpack.github.io/docs/tutorials/getting-started/)
- [Documentazione Node Package Manager (NPM)](https://docs.npmjs.com/)
- [Pagina di download Node](https://nodejs.org/en/download/)
- [Usare un file Package.json](https://docs.npmjs.com/getting-started/using-a-package.json)
- [Un'introduzione a ES6 e NPM](http://wesbos.com/javascript-modules/)
