# Component Class React {#class-components}

Come menzionato in [_Introduzione a React_](#react), e' anche possibile definire React Components usando la sintassi class ES6:

```jsx
//Definisci un class component che rappresenta informazioni su un user
class UserInfo extends React.Component {
    //I Components DEVONO fare override della function `render()`, che deve restituire un
    //elemento DOM
    render() {
        //Questa e' una function normale; puoi includere qui qualsiasi codice vuoi
        let name = "Ethel";
        let descriptor = "Aardvark";

        //Restituisci un React element (JSX) che e' come apparira' il component
        return (
            <div>
                <h1>{name}</h1>
                <p>Ciao, mi chiamo {name} e sono un {descriptor}</p>
            </div>
        )        
    }
}
```

Questo capitolo contiene ulteriori dettagli su come lavorare con questo stile di **Class Components**, in particolare su come gestire lo _state_ all'interno di tali components. Questo capitolo puo' quindi essere letto come uno specchio di [_React Interattivo_], solo usando class components invece di function components.

<p class="alert alert-info">Questo capitolo e' tratto da una versione precedente del testo che enfatizzava i class components invece dei function components.</p>

## Props nei Class Components 
Quando definisci un Class component, tutte le props passate vengono assegnate automaticamente alla instance variable `props`, accessibile come **`this.props`**. La variable `this.props` contiene l'object che verrebbe passato come argomento a una versione function del component. 

```jsx
//Definisci un component che rappresenta informazioni su un user
class UserInfo extends Component {
    render() {
        //accedi alle singole props dall'interno dell'object `this.props`
        let userName = this.props.userName;
        let descriptor = this.props.descriptor;

        return (
            <div>
                <h1>{userName}</h1>
                <p>Ciao, mi chiamo {name} e sono un {descriptor}</p>
            </div>
        )        
    }
}

let userInfo = <UserInfo userName="Ethel" descriptor="Aardvark" />;
```

Nota che l'object `this.props` e' **read only**&mdash;cioe' non puoi assegnargli nuovi values, ne' modificare direttamente le sue props. Dovresti pensare alle props come data immutabili che arrivano dall'esterno del component (di nuovo, simile agli argomenti di una function). Un component non crea o cambia le proprie props, le usa solo per determinare come renderizzare il suo contenuto.

## Gestire gli Eventi nei Class Components
Quando usi class components, gli eventi vengono gestiti nello stesso modo dei function components (per esempio, usando la prop `onClick`). La differenza principale e' che le callback di event handler sono di solito definite come _methods_ separati della class:

```jsx
//Un component che rappresenta un button che logga un messaggio quando viene cliccato
class MyButton extends Component {
  //method da chiamare quando si clicca. Il nome e' convenzionale, ma arbitrario
  //la callback function ricevera' l'event del DOM
  handleClick(event) {
     console.log('clic clic');
  }
  render() {
    //crea un button con un attribute `onClick`!
    //questo "registra" il listener e imposta la callback
    return <button onClick={this.handleClick}>Cliccami!</button>;
  }
}
```

Nota che quando assegni il method alla prop `onClick`, il method viene referenziato usando la keyword `this` (e senza parentesi!), perche' il riferimento e' al method `handleClick()` di _questo Component_.

### Accedere al `this` del Component dagli Eventi {-}
E' molto comune che le event callback functions di un Component debbano referenziare le instance variables o i methods di quel component&mdash;per esempio, per fare qualcosa in base a una prop (trovata in `this.props`) o per chiamare un helper method aggiuntivo (chiamato come `this.otherMethod()`). In breve&mdash;la event callback dovra' avere accesso al contesto `this`. 

Ma come discusso in [Sezione 15.2](#working-with-this), le callback functions non vengono chiamate su alcun object specifico, e quindi non hanno un value assegnato alla loro variable `this`. Nell'esempio sopra, anche se stai usando la parola `this` per _referenziare_ il method `this.handleClick` (per dire a JavaScript dove trovare la function), quella function non viene realmente chiamata sulla class. Come descritto nella Sezione 15.2, solo perche' il method e' stato definito dentro una class non significa che debba essere chiamato su una instance di quella class!

```jsx
//BUGGY CODE: Un button che causa un errore quando viene cliccato!
class MyButton extends Component {
  handleClick(event) {
     //Riferisci la instance variable `this.props` dell'object. Ma dato che `this`
     //e' undefined quando viene eseguita come callback, causerebbe un
     //TypeError: Cannot read property 'props' of undefined
     console.log("Hai cliccato su", this.props.text)
  }

  render() {
    //Specifica una function (che capita essere un class method) come callback
    return <button onClick={this.handleClick}>{this.props.text}</button>;
  }
}

//Renderizza il component, passandogli una prop
ReactDOM.render(<MyButton text="Cliccami!"/>, document.getElementById('root'));
```

Quindi, dovrai assicurarti di "mantenere" il contesto `this` quando specifichi una event callback function. Ci sono alcuni modi per farlo. 

- Primo, come descritto nel Chapter 15, una _arrow function_ usera' lo stesso `this` lessicale del contesto in cui e' definita. Quindi puoi "wrappare" la event callback function in una arrow function per mantenere il `this`, chiamando quel method sulla instance `this` in modo esplicito:

    ```jsx
    class MyButton extends Component {
      handleClick(event) {
         console.log("Hai cliccato su", this.props.text) //funziona come previsto!
      }

      render() {
        return (
            <button onClick={(evt) => this.handleClick(evt) }>
                {this.props.text}
            </button>
        )
      }
    }
    ```

    In questo esempio, al listener `onClick` viene passata una callback function anonima (sotto forma di arrow function), che fa il lavoro di chiamare il method `handleClick()` sulla instance (`this`). In effetti, stai definendo una "ricetta temporanea" da registrare con l'event listener, la cui unica istruzione e' "segui quest'altra ricetta". Nota che questo approccio ha anche il vantaggio di permetterti di passare argomenti aggiuntivi alla event callback!

    React nota che questo approccio puo' avere una penalita' di performance&mdash;stai creando una nuova function (la arrow function) ogni volta che il component viene renderizzato, e i components possono essere renderizzati _molte_ volte quando rendi interattive le React apps! Questo non sara' evidente all'inizio, ma puo' iniziare a fare la differenza per applications su larga scala.
    
- Un approccio alternativo e' usare un [**public class field**](https://github.com/tc39/proposal-class-fields) per definire il method. Questa e' una sintassi JavaScript _sperimentale_&mdash;attualmente e' in considerazione per l'inclusione ufficiale nel linguaggio JavaScript. Tuttavia, il transpiler Babel supporta questa sintassi (trasformandola in una class function bound), e questo supporto e' abilitato in Create React App, permettendoti di usare la sintassi _per React apps_.

    Un _public class field_ e' un field (instance variable) a cui viene assegnato un value al "top level" di una class, invece di assegnarlo esplicitamente a una property di `this` nel constructor.

    ```js
    //Una class con un public class field
    class Counter {
        x = 0; //assegna il value qui, non nel constructor
        
        increment() {
            this.x = this.x + 1; //puoi accedere al field come al solito
        }    
    }
    
    let counter = new Counter();
    counter.increment();
    console.log(counter.x); //stampa 1    
    ```

    Ma dato che puoi assegnare qualsiasi tipo di value a un field&mdash;incluse le functions&mdash;puoi usare un public class field e definire la event callback, usando una arrow function per mantenere il contesto `this` bound:
    
    ```jsx
    class MyButton extends Component {
      //definisci la event callback come public class field (usando una arrow function)
      handleClick = (event) => {
         console.log("Hai cliccato su", this.props.text) //funziona come previsto!
      }

      render() {
        return <button onClick={this.handleClick}>{this.props.text}</button>;
      }
    }
    ```
    
    Anche se e' un po' piu' difficile da leggere e interpretare (in particolare se la callback non prende parametri), questo approccio ti permette di specificare una function bound (che avra' il value corretto di `this`), pur potendo referenziare la function direttamente quando registri l'event listener&mdash;senza doverla wrappare in una arrow function separata. Al momento della scrittura, questo approccio e' il modo "cool" in cui le callback functions vengono specificate in React.


## State nei Class Components {#state-in-class-components}
I React Components memorizzano il loro state nella instance variable `state` (accessibile come **`this.state`**). A differenza delle props che sono specificate come input al Component, lo state deve essere inizialmente assegnato a un value, cosa che dovrebbe essere fatta nel _constructor_ del Component:

```jsx
//Un button che traccia quante volte e' stato cliccato
class CountingButton extends Component {
  constructor(props) { //il constructor deve prendere un parametro `props`
     super(props)      //il constructor deve chiamare il superclass constructor

     //inizializza lo state del Component
     this.state = {
         count: 0 //un value contenuto nello state
     }
  }

  render() {
    //puoi _accedere_ ai values dello state nella function `render()`
    return <button>Mi hai cliccato {this.state.count} volte</button>;
  }
}
```

Poiche' i Components _ereditano_ (extend) la class `React.Component`, i loro constructors devono fare lo stesso lavoro della parent class (cosi' possono funzionare nello stesso modo). In particolare, il constructor deve prendere un singolo parametro (che rappresenta le props passate al Component). Deve poi chiamare immediatamente la versione del constructor del parent (e passare quelle props) usando `super(props)`. Questo fara' si' che le props siano impostate correttamente, cosi' puoi usarle normalmente.
 
Dentro il constructor, _inizializzi_ il value `this.state` (e di solito e' tutto cio' che fai nel constructor!). Il value `this.state` deve essere un Object JavaScript che puo' memorizzare data specifici&mdash;non puoi fare dello state una String o un Number, ma un object che puo' contenere Strings e/o Numbers (con keys per etichettarli).

Puoi accedere ai values attualmente memorizzati nello state tramite la instance variable `this.state`. Di solito lo fai in `render()` (o in un helper method chiamato dalla function `render()`). Se un value non viene usato per il rendering, probabilmente non deve far parte dello state!

I React Components devono memorizzare il loro state nella instance variable `state` (accessibile come **`this.state`**). A differenza delle props che sono specificate come input al Component, lo state deve essere inizialmente assegnato a un value, cosa che dovrebbe essere fatta nel _constructor_ del Component:

```jsx
//Un button che traccia quante volte e' stato cliccato
class CountingButton extends Component {
  constructor(props) { //il constructor deve prendere un parametro `props`
     super(props)      //il constructor deve chiamare il superclass constructor

     //inizializza lo state del Component
     this.state = {
         count: 0 //un value contenuto nello state
     }
  }

  render() {
    //puoi _accedere_ ai values dello state nella function `render()`
    return <button>Mi hai cliccato {this.state.count} volte</button>;
  }
}
```

Poiche' i Components _ereditano_ (extend) la class `React.Component`, i loro constructors devono fare lo stesso lavoro della parent class (cosi' possono funzionare nello stesso modo). In particolare, il constructor deve prendere un singolo parametro (che rappresenta le props passate al Component). Deve poi chiamare immediatamente la versione del constructor del parent (e passare quelle props) usando `super(props)`. Questo fara' si' che le props siano impostate correttamente, cosi' puoi usarle normalmente.
 
Dentro il constructor, _inizializzi_ il value `this.state` (e di solito e' tutto cio' che fai nel constructor!). Il value `this.state` deve essere un Object JavaScript che puo' memorizzare data specifici&mdash;non puoi fare dello state una String o un Number, ma un object che puo' contenere Strings e/o Numbers (con keys per etichettarli).

Puoi accedere ai values attualmente memorizzati nello state tramite la instance variable `this.state`. Di solito lo fai in `render()` (o in un helper method chiamato dalla function `render()`). Se un value non viene usato per il rendering, probabilmente non deve far parte dello state!

### Cambiare lo State {-}
I data sono memorizzati nello state cosi' possono essere cambiati nel tempo. Puoi modificare lo state di un Component chiamando il method [**`setState()`**](https://reactjs.org/docs/react-component.html#setstate) su quel Component. Questo method di solito prende come parametro un object che contiene i nuovi values desiderati per lo state; questo set di nuovi values verra' "merged" nello state esistente, cambiando solo i values indicati (gli altri values rimarranno invariati):

```jsx
//Un elemento che mostra l'orario quando richiesto
class Clock extends Component {
  constructor(props) {
     super(props)
     this.state = {
         currentTime: new Date(), //orario corrente
         alarmSound: "annoying_buzz.mp3" //suono allarme modificabile
     }
  }

  //callback function per il button (public class field)
  handleClick = (props) => {
     let stateChanges = { 
          currentTime: new Date() //nuovo value da salvare nello state
     };
     this.setState(stateChanges); //applica i cambiamenti di state e re-renderizza!
  }
  
  render() {
      return (
          <div>
            <button onClick={this.handleClick}>Che ore sono adesso</button>
            <p>L'ora e' {this.state.currentTime.toLocaleTimeString()}</p>
          </div>
      );
  }
}
```

Il method `setState()` ["merge"](https://reactjs.org/docs/state-and-lifecycle.html#state-updates-are-merged) i values del suo parametro nel field `state` del Component; nell'esempio sopra, il value `alarmSound` non verra' modificato quando il button viene premuto; solo il value di `currentTime` verra' cambiato. Se vuoi cambiare piu' values allo stesso tempo, puoi includere piu' keys nel parametro di `setState()`. Nota anche che questo merging e' "shallow"&mdash;se volessi cambiare un value di state che e' un array (per esempio, `this.state = { comments:[...] }`), dovresti impostare una versione completamente nuova di quell'array (che puo' essere una versione modificata dello state precedente; vedi sotto).
 
In modo importante, _devi_ usare il method `setState()` per cambiare lo state; [_non puoi_](https://reactjs.org/docs/state-and-lifecycle.html#do-not-modify-state-directly) assegnare direttamente un nuovo value alla instance variable `this.state`. Questo perche' il framework React usa quel method non solo per aggiornare la instance variable, ma anche per far "re-renderizzare" il Component. Quando lo state ha finito di aggiornarsi, React re-renderizza il Component (facendo richiamare il method `render()`), e mergea il rendering aggiornato nel DOM della pagina. React fa questo merging in modo altamente efficiente, cambiando gli elementi che sono effettivamente aggiornati&mdash;questo e' cio' che rende React cosi' efficace per sistemi su larga scala.

<p class="alert alert-info">Ricorda: chiamare `setState()` fara' chiamare di nuovo il method `render()`, e accedera' ai values `this.state` aggiornati!</p>

<p class="alert alert-danger">Never chiamare `setState()` direttamente dall'interno di `render()`! Causerebbe un loop ricorsivo infinito. Il method `render()` deve rimanere "pure" senza side effects.</p>

Inoltre, il method `setState()` e' [_asynchronous_](https://reactjs.org/docs/state-and-lifecycle.html#state-updates-may-be-asynchronous). Chiamare il method invia solo una "request" per aggiornare lo state; non avviene immediatamente. Questo perche' React "batcha" piu' request per aggiornare lo state dei Components (e quindi per rerenderizzarli) insieme&mdash;in questo modo se la tua app deve fare molti piccoli cambiamenti nello stesso momento, React ha bisogno di rigenerare il DOM solo una volta, fornendo un notevole boost di performance.

```jsx
//Un Component con una callback che non gestisce i cambiamenti di state asincroni
class CounterWithError extends Component {
  constructor(props) {
     super(props)
     this.state = {
         count: 3 //value iniziale
     }
  }

  handleClick = () => {
     this.setState({count: 4}); //cambia `count` a 4
     console.log(this.state.count); //stampera' "3"; lo state non e' ancora cambiato!
  }
  
  //...
}
```

In questo esempio, poiche' `setState()` e' asynchronous, non puoi accedere immediatamente allo state aggiornato dopo aver chiamato la function. Se vuoi usare quel value aggiornato, devi farlo nel method `render()`, che verra' chiamato di nuovo una volta che lo state ha finito di aggiornarsi.

Poiche' le chiamate a `setState()` sono asynchronous e possono essere batchate, se vuoi aggiornare un value di state basato sullo state _corrente_ (per esempio, per aumentare un contatore), devi invece passare al method `setState()` una [_callback function_](https://reactjs.org/docs/state-and-lifecycle.html#state-updates-may-be-asynchronous) come argomento (invece di un Object di nuovi values). La callback function ricevera' lo state "corrente" (e le props), e deve `return`are l'Object che vuoi mergeare nello state:

```jsx
//Un esempio di callback per il click del button
class Counter extends Component {
  constructor(props) {
     super(props)
     this.state = { count: 0 } //value iniziale
  }

  handleClick = () => {
     //setState riceve una callback function anonima
     this.setState((currentState, currentProps) => {
         //restituisci l'Object da "mergeare" nello state
         let stateChanges = {count: currentState.count + 1}; //incrementa count
         return stateChanges;
     })
  } 
   
  //...
}
```

Anche se provare a usare `this.state` direttamente in una chiamata a `setState()` _a volte_ funziona, la best practice e' usare una callback function come sopra quando il nuovo value di state dipende dal vecchio.

## Il Lifecycle del Component
Lo state di un react component viene inizializzato nel constructor (quando il component viene istanziato per la prima volta), e poi di solito modificato in risposta a eventi dello user (chiamando il method `setState()`). Ma ci sono molti altri "eventi" che avvengono durante la vita di un Component&mdash;come gli "eventi" di quando il Component viene aggiunto al DOM ("mounted") o rimosso dal DOM ("unmounted"). Per esempio, dovresti scaricare i data solo quando c'e' un Component sullo schermo per mostrare quei data (dopo che il Component e' stato aggiunto al DOM), e "pulire" qualsiasi listener o timer quando il Component viene rimosso.
E' possibile definire functions che verranno eseguite in questi eventi, permettendoti di eseguire azioni specifiche mentre il framework React manipola il DOM. Queste functions sono chiamate [**lifecycle methods**](https://reactjs.org/docs/state-and-lifecycle.html#adding-lifecycle-methods-to-a-class)&mdash;sono methods che vengono eseguiti in diverse fasi del "lifecycle" del Component. Tu _override_ questi lifecycle methods per specificare quale codice vuoi eseguire in quegli eventi. I lifecycle methods verranno _automaticamente eseguiti dal framework React_; non li chiami mai direttamente (allo stesso modo in cui non chiami mai direttamente `render()`&mdash;che e' essa stessa un lifecycle method!)

I react components hanno diversi lifecycle methods, i piu' comuni dei quali sono illustrati qui sotto:

```jsx
//Un component generico
class MyComponent extends Component {
  //Il constructor viene chiamato quando il Component e' istanziato, ma prima
  //che venga aggiunto al DOM (sullo schermo)  
  constructor(props){
    super(props)
    //inizializza lo state qui!
  }

  //Questo method viene chiamato quando il Component e' stato aggiunto al DOM (ed
  //e' visibile sullo schermo). Questo avviene _dopo_ la prima chiamata a `render()`.
  componentDidMount() {
    //fai qui il lavoro di setup (asynchronous), incluse le request AJAX!
  }
  
  //Questo method viene chiamato quando un Component viene "re-renderizzato" con un
  //nuovo set di props. Questo e' un method meno comune da override
  componentDidUpdate(prevProps, prevState, snapshot) {
    //fai qui lavoro aggiuntivo di "re-setup" (incluse request AJAX aggiornate)!
  }

  //Questo method viene chiamato quando il Component sta per essere rimosso dal DOM
  //(e quindi non sara' piu' visibile sullo schermo)
  componentWillUnmount() {
    //fai qui il lavoro di cleanup (asynchronous)!
  }  
}
```

Per maggiori dettagli sugli usi specifici (e i parametri!) di questi methods, vedi la [documentazione ufficiale API](https://reactjs.org/docs/react-component.html#the-component-lifecycle). 

<!-- Is there more to say about this? :/ -->

Nota che non sei _obbligato_ a includere questi methods in un Component. Tuttavia, sono necessari per eseguire correttamente functions asynchronous come le request AJAX, come descritto sotto.


### Esempio di Lifecycle: Caricare Data via AJAX {-}
Uno degli usi piu' comuni delle lifecycle callback functions e' quando si accede a data in modo asincrono, ad esempio quando si scaricano data tramite una request AJAX (come descritto in [Chapter 14](#ajax)). Questa sezione fornisce dettagli su come caricare data in modo asincrono dentro un React class component.

Ricorda che la function `fetch()` scarica i data in modo _asynchronous_. Quindi se vuoi scaricare dei data da mostrare, potrebbero impiegare un po' ad arrivare. Non vuoi che React debba "aspettare" i data (dato che React e' progettato per essere _fast_). Quindi la best practice e' inviare la request `fetch()` per i data e poi, `then`, quando i data sono stati scaricati, chiamare il method `setState()` per aggiornare il Component con i data scaricati. (Il Component puo' inizializzare il suo state come un "array vuoto" di data).

Poiche' `fetch()` alla fine chiamera' il method `setState()`, non puoi inviare l'AJAX dal constructor del Component. Questo perche' `setState()` alla fine renderizzera' il Component, il che implica aggiornare qualcosa che e' stato aggiunto al DOM. Nel constructor, il Component e' stato istanziato, ma non e' ancora stato aggiunto al DOM&mdash;quindi non puoi ancora aggiornare il suo state! Se i data finiscono per scaricarsi prima che il Component sia mounted, otterrai un errore che dice che non puoi re-renderizzare un Component non mounted!

Invece, dovresti sempre inviare le tue (iniziali) request `fetch()` dal lifecycle method `componentDidMount()`. In questo modo i data verranno scaricati solo quando il Component e' stato effettivamente aggiunto al DOM, e quindi e' disponibile per il re-rendering. Questa struttura e' mostrata nell'esempio sotto:

```jsx
class MyComponent extends Componet {
  constructor(props){
    super(props);
    this.state = {
        data: [] //inizializza i data come "vuoti"
    }; 
  }

  componentDidMount() {    
    fetch(dataUri) //invia una request AJAX
      .then((res) => res.json())
      .then((data) => {
        let processedData = data.filter(...).map(...) //fai il processing desiderato
        this.setState({data: processedData}) //cambia lo state, e re-renderizza
      })
  }

  render() {
    //Mappa i data values in elementi DOM
    //Nota che questo funziona anche prima che i data siano caricati (quando l'array e' vuoto!)
    let dataItems = this.state.data.map((item) => {
      return <li key={item.id}>{item.value}</li>; //restituisce la versione DOM del datum
    })

    //renderizza i data items (per esempio, come list)
    return <ul>{dataItems}</ul>; 
  }
}
```

Nell'esempio sopra, `this.state.data` e' inizializzato come array vuoto; questo `render()` funziona benissimo (produce una list vuota). Una volta che il Component e' mounted, i data verranno scaricati e processati, e poi salvati come value di state aggiornato. Chiamare `setState()` fara' re-renderizzare il Component, cosi' che i data vengano mostrati come desiderato! Anche se tecnicamente significa che il Component renderizza due volte, React puo' batchare queste request insieme cosi' se i data si scaricano abbastanza velocemente, lo user non se ne accorgera'.

## Risorse {-}

<div class="list-condensed">
- [Il Lifecycle del Component](https://reactjs.org/docs/react-component.html#the-component-lifecycle)
- [State e Lifecycle](https://reactjs.org/docs/state-and-lifecycle.html)
</div>
