# Routing lato client
Questo capitolo discute come usare React per sviluppare efficacemente **Single Page Applications (SPA)**&mdash;web applications che si trovano su una singola web page (file HTML), ma con manipolazione del DOM (e spesso request AJAX) per produrre l'_aspetto_ di piu' "web pages". Questa struttura e' facilitata dall'uso della library di _client-side routing_ `react-router`, che ti permette di renderizzare Components diversi in base all'URL del browser, permettendo a ciascuna View ("pagina") di essere trattata come una [risorsa](https://en.wikipedia.org/wiki/Web_resource) unica.


## Single-Page Applications
Come hai visto nei capitoli precedenti, il framework React ti permette di renderizzare dinamicamente _Views_ (Components) diverse in base a condizioni diverse come lo `state` dell'app. Per esempio, puoi avere una blogging app che potrebbe avere una state variable `blogPostId`, e poi usare quella variable per determinare quale blog post visualizzare. Spesso queste Views agiscono come **pagine** completamente separate&mdash;mostri una View o un'altra. Di conseguenza, spesso vuoi che ogni View sia trattata come una _risorsa_ individuale e quindi abbia il suo [**URI**](https://en.wikipedia.org/wiki/Uniform_Resource_Identifier), permettendo a ciascuna View di essere referenziata individualmente. Per esempio, ogni blog post potrebbe avere il proprio URI, permettendo a uno user di digitare un URL specifico per vedere un post specifico (e permettendo a quello user di condividere il post con altri).

<!-- - Anche se potresti ottenere URI unici facendo si' che ogni View sia un file HTML separato (per esempio, `index.html`, `about.html`), questo diventa rapidamente impraticabile per una grande quantita' di risorse, come quando vuoi creare una nuova "web page" per ogni blog post memorizzato in un database. Inoltre, file `.html` separati non sarebbero in grado di condividere data/state o components (per esempio, un elemento di navigazione condiviso). -->

Per ottenere questo effetto, puoi usare il **client-side routing**. Con il client-side routing, determinare quale View mostrare in base all'URL (come "instradare", o mappare quell'URL alla risorsa corretta) viene eseguito lato _client_ dal codice JavaScript. Questo e' distinto dal _server-side routing_, in cui il server non decide quale risorsa mostrare (cioe', a quale file `.html` rispondere a una request), ma risponde invece con un singolo file HTML il cui JavaScript determina dinamicamente quale risorsa mostrare (cioe', quale React component renderizzare) in base all'_URI_ a cui e' stata inviata la request!

- In questo contesto, "routing" significa prendere l'identificatore della risorsa (l'URI) e determinare quale _rappresentazione_ di quella risorsa dovrebbe essere mostrata&mdash;quale View mostrare. Una "route" e' quindi un URI, che si riferira' a una particolare View della risorsa.

Il client-side routing ti permette di avere URL unici per ogni View, ma rende anche l'app piu' veloce&mdash;invece di dover scaricare una pagina completamente nuova dal server, devi scaricare solo i data extra necessari (per esempio, usando una request AJAX), con gran parte degli altri contenuti (HTML, CSS, ecc.) gia' in posizione. Inoltre, questo permettera' alla tua app di condividere facilmente sia i data di state che components specifici (per esempio, header, navigazione, ecc.).

- [Google Drive](https://drive.google.com) e' un buon esempio di Single-Page Application. Nota come se navighi in una nuova cartella, l'URL cambia (cosi' puoi linkare cartelle specifiche), ma cambia solo un singolo "pane" della pagina.


Poiche' le React applications sono basate su componenti, puoi fare _client-side routing_ in React usando la [conditional rendering](https://reactjs.org/docs/conditional-rendering.html) per renderizzare components solo se la route corrente e' corretta. Questo segue una struttura simile a:

```jsx
function App(props) {
    //scegli un component in base all'URL
    let componentToRender = null;
    if(currentUrl === '/home'){ //confronto in pseudocodice con l'URL
        componentToRender = <HomePage />;
    }
    else if(currentUrl === '/about'){
        componentToRender = <AboutPage />;
    }
    //renderizza quel component
    return componentToRender;
}
```

Cioe', _se_ l'URL corrente **matcha** una route particolare, allora il Component verra' renderizzato.


## React-Router
Libraries di terze parti come [**React Router**](https://reactrouter.com/en/6.4.4) forniscono Components che includono questa funzionalita' di "matching", permettendoti di sviluppare facilmente single-page applications.

<p class="alert alert-warning">Questo capitolo descrive come usare la [**version 7**](https://reactrouter.com/7.1.5/home) di React Router, rilasciata in _November 2021_. Questa versione e' significativamente diversa dalle versioni precedenti (in particolare v5). Fai attenzione quando cerchi esempi e risorse che stiano utilizzando la tua stessa versione! Per dettagli sulle versioni precedenti di React Router, vedi [la documentazione per quelle versioni](https://v5.reactrouter.com/). In modo importante, questo capitolo insegna come usare React Router come **library**, non come Framework.</p>

Come con altre libraries, inizi a [usare React Router](https://reactrouter.com/7.1.5/start/library/installation) installando la library `react-router`:

```bash
npm install react-router
```

Dovrai poi `import`are qualsiasi Component tu voglia usare nei file `.js` che contengono il tuo codice React. Per esempio:

```js
//importa BrowserRouter, Routes, Route e Link da react-router
import { BrowserRouter, Routes, Route, Link} from 'react-router'
```

Questi Components sono descritti nelle sezioni seguenti.

### Routing {-}
Il Component **`<BrowserRouter>`** (che spesso viene importato con l'alias `<Router>`&mdash;anche se esiste anche un component `<Router>`!) e' il Component "base" usato da React Router. Questo Component fa tutto il lavoro di mantenere l'UI della React app (per esempio, quali Components sono renderizzati) in sync con l'URL del browser. `BrowserRouter` "ascolta" i cambiamenti dell'URL, e poi passa informazioni sulla route corrente (chiamata **`path`**) ai suoi child components. Questo permette a ciascun child di sapere sempre quale route e' attualmente mostrata nell'URL, senza dover accedere direttamente all'URL.

- Con React Router, una "route" e' definita dalla parte _path_ di un URI (vedi [Chapter 2](#http-requests-and-servers)). Questa e' la parte che viene _dopo_ protocollo e dominio (per esempio, dopo `https://mydomain.com/`). Quindi la route `/home` si riferirebbe all'URI `https://mydomain.com/home`, mentre la route `/about` si riferirebbe all'URI `https://mydomain.com/about`.

- `BrowserRouter` utilizza la [HTML5 history API](https://developer.mozilla.org/en-US/docs/Web/API/History_API) per interagire con l'URL e la history del browser (quello che ti permette di andare "indietro" e "avanti" tra URL). Questa API e' supportata dai [modern browsers](https://caniuse.com/#feat=history), ma i browser piu' vecchi (cioe', IE 9) dovrebbero usare `<HashRouter>` come alternativa drop-in. `HashRouter` usa la parte [fragment identifier](https://en.wikipedia.org/wiki/Fragment_identifier) dell'URI per tracciare quale "pagina" l'app dovrebbe mostrare, facendo si' che gli URL includano un simbolo hash `#` extra (per esempio, `https://mydomain.com/#/about`).

- La tua app avra' sempre un solo component `<BrowserRouter>` al suo interno--di solito al "top level" della tua application (quindi conterrebbe `<App>` come child). Quindi `<BrowserRouter>` di solito viene renderizzato nel file `index.html`:

    ```jsx
    //index.js

    import { BrowserRouter } from 'react-router'
    import App from './components/App.js'

    //renderizza l'App *dentro* il BrowserRouter
    const root = ReactDOM.createRoot(document.getElementById('root'));
    root.render(
        <BrowserRouter>
            <App />
        </BrowserRouter>
    );
    ```

Dentro `<BrowserRouter>` (di solito dentro `<App>`), definirai le **routes** per la tua application&mdash;la collezione di paths supportati e quale View mostrare per ciascuno. Puoi specificare views basate su route usando il Component **`<Route>`**. Questo component renderizzera' il suo **`element`** solo quando l'URL corrente _matcha_ un **`path`** specificato. In effetti, il Component `Route` gestisce il controllo _`if`_ che l'URL corrente matchi il path specificato, e se cosi' rende il suo element. Se l'URL non matcha la route, allora l'element non viene renderizzato. Sia il `path` che l'`element` vengono passati al `<Route>` come props:

```jsx
function App(props) {
    return (
        <Routes> {/* la collezione di routes da matchare */}
            {/* if currentUrlPath === "home" */}
            <Route path="home" element={<HomePage />} />

            {/* if currentUrlPath ===  "about" */}
            <Route path="about" element={<AboutPage />} />
        </Routes>
    );
}
```

Cose da notare su questo esempio:

- La prop `path` e' usata per indicare la route che vuoi matchare&mdash;in particolare, il matching alla parte _path_ dell'URL (dopo il domain). Non includi `http` o `domain.com` nel path.

    Il segmento "root" `"/"` e' usato per matchare un URL senza path (per esempio, cosa mostrare a `http://domain.com`). Usare un wildcard `*` nel path matchera' "qualunque cosa", ed e' utile per renderizzare elementi "Page Not Found".

    Il path puo' includere piu' segmenti (per esempio, `assignments/react`); tuttavia piu' segmenti di solito corrispondono a [_nested routes_](#nesting-routes), descritte sotto.

- Il Component (View) da renderizzare viene passato come prop `element`. Istanzi il component usando la sintassi `<Component/>`, e poi lo passi come inline expression (dentro `{}`). Si', rende la sintassi un po' scomoda.

    Naturalmente puoi passare props aggiuntive al component renderizzato come al solito:

    ```jsx
    <Route path="profile" element={<ProfilePage user={userData} />} />
    ```

    Anche se e' possibile passare elementi _nested_ come property `element`, questo puo' diventare rapidamente un incubo di leggibilita'. La best practice e' definire un singolo Component "wrapper" da renderizzare nella Route.

- _Tutti_ gli elementi `<Route>` sono children di un _singolo_ elemento chiamato **`<Routes>`** (nota che la `s` lo rende plurale!). L'elemento `<Routes>` rappresenta la "collezione" di Routes tra cui il Router deve scegliere quando decide quale Component renderizzare (se c'e'). Puoi pensarlo come un `switch` statement.

    In pratica, avrai un singolo elemento `<Routes>` nella tua pagina, di solito in un component top-level come `<App>`.

    Nota che un `<Routes>` puo' avere _solo_ elementi `<Route>` come children, e un elemento `<Route>` puo' essere _solo_ child di un `<Routes>`. Vanno insieme, e nient'altro (nessun altro `<div>`, ecc.) puo' stare tra di loro. Anche se vedi [_Nesting Routes_](#nesting-routes) per dettagli su come integrare layout DOM diversi con il routing.


#### Nesting Routes {-}
Nell'esempio sopra, la prop `path` della Route corrisponde a un singolo **segmento** del path dell'URI. Molte React apps vogliono differenziare il contenuto renderizzato in base a _piu' segmenti_. Per esempio: il path `/user/profile` potrebbe mostrare un component `<UserProfile>`, mentre il path `user/favorites` potrebbe mostrare un component `<FavoriteItems>` (con la lista degli items che lo user ha contrassegnato). Eppure entrambi questi path potrebbero anche voler mostrare contenuti condivisi da tutte le Views che fanno parte dei path `/user` (ma diversi da altri path non specifici dell'utente, come il path `/items`).

React Router supporta questo comportamento tramite **nesting routes**&mdash;avendo un elemento `<Route>` come child di un altro. Per esempio:

```jsx
// Un esempio di nested routes
<Routes>
    <Route path="user" element={<UserLayout />} >
        <Route path="profile" element={<UserProfile />} />
        <Route path="favorites" element={<FavoriteItems />} />
    </Route>
    <Route path="items" element={ <ItemList />} />
</Routes>
```

Quando l'elemento `<Routes>` deve matchare un URL e determinare quale elemento renderizzare, iniziera' dal primo _segmento_ del path, renderizzando quell'elemento. Per esempio, se il path inizia con `/user`, allora il Router renderizzera' l'elemento `<UserLayout>`. Ma poi continuera' a controllare ulteriori segmenti del path: quindi se il path e' `/user/profile`, allora il Router renderizzera' `<UserLayout>` (per la parte `/user`), ma poi renderizzera' `<UserProfile>` (per la parte `/profile`) _dentro_ `<UserLayout>` in una location indicata. Quindi potresti vedere le Routes sopra come definire i seguenti path:

- `/user/profile` renderizza `<UserLayout><UserProfile/></UserLayout>`
- `/user/favorites` renderizza `<UserLayout><UserFavorites/></UserLayout>`
- `/user` renderizza `<UserLayout></UserLayout>` (nessun child)
- `/items` renderizza `<ItemList />`

(Puoi pensare a ogni step di "nested child" come a un `/` nel path)

Specifichi _dove_ nel parent element il child element renderizzera' usando un Component **`<Outlet>`**. Questo component verra' sostituito dall'elemento della child route che matcha il segmento dell'URL:

```jsx
function UserLayout(props) {
    render (
        <div className="user-layout">
            <h1>Pagina utente</h1>
            {/* verra' sostituito con <UserProfile>, <UserFavorites> o null */}
            <Outlet />
        </div>
    )
}
```

Quindi puoi pensare a `<Outlet />` come al "posto dove andra' il child component".

Le nested routes sono usate principalmente per creare layout condivisi, come nell'esempio sopra. Il component `<UserLayout>` puo' contenere elementi di struttura (come i div) che verranno condivisi tra le routes che iniziano con lo stesso segmento, ma non tra altre routes.

<div class="alert alert-warning"><p>Non tutte le apps richiedono il nesting delle routes! Se tutta la tua app ha un singolo layout, non devi creare un Component separato per questo; puoi semplicemente renderizzarlo come parte del tuo `<App>` e usare `<Routes>` per specificare il contenuto dinamico.</p>
<p>Allo stesso modo, ricorda che le Routes servono **solo** per renderizzare condizionalmente un Component _basato sull'URI_. Se vuoi mostrare contenuti in modo condizionale (per esempio, a seconda che lo user sia loggato, o in base a quale item e' stato selezionato), usa la [conditional rendering](https://react.dev/learn/conditional-rendering) basata sullo state&mdash;non usare una Route!</p></div>

Se vuoi mostrare un child Component "di default" quando non c'e' un ulteriore segmento, puoi dare alla child Route la prop **`index`**:

```jsx
<Routes>
    <Route path="user" element={<UserLayout />} >
        {/* mostra UserHome a ``/user` */}
        <Route index element={<UserHome />} />
        <Route path="profile" element={<UserProfile />} />
        <Route path="favorites" element={<FavoriteItems />} />
    </Route>
</Routes>
```

Nota che la prop `index` (che non prende altri values!) di fatto "sostituisce" il segmento `path` per quel child.

<div class="alert alert-info">Spesso e' utile specificare le routes come una variable `const` (per esempio, `routes`) che e' un object contenente i paths e quale component renderizzare per quel path. Puoi usare l'hook `useRoutes()` per renderizzare questo object _invece_ di specificare un elemento `<Routes>`. Questo e' consigliato solo per applications particolarmente grandi.</div>

Puoi usare l'hook `useMatch()` per accedere al `path` corrente; questo puo' essere utile per specificare, per esempio, path relativi delle immagini.


#### URL Parameters {-}
E' anche possibile includere _variables_ nella route matchata usando i cosiddetti **URL Parameters**. Come potresti ricordare dalla [lettura di una RESTful API](https://info201.github.io/apis.html#uris), gli endpoint URI sono spesso specificati con "variables" scritte usando la sintassi **`:param`** (due punti `:` seguiti dal nome del parametro). Per esempio, l'URI

```
https://api.github.com/users/:username
```

dal [Github API](https://developer.github.com/v3/users/) si riferisce a uno user specifico&mdash;puoi _sostituire_ `:username` con qualsiasi value vuoi: `https://api.github.com/users/joelwross` si riferisce allo user `joelwross` (quindi `username = 'joelwross'`), mentre `https://api.github.com/users/mkfreeman` si riferisce allo user `mkfreeman` (quindi `username = 'mkfreeman'`).

React Router supporta una sintassi simile quando specifichi i path delle Route. Per esempio:

```jsx
<Route path='posts/:postId' element={<BlogPost />} />
```

matchera' un path che inizia con `posts/` ed e' seguito da qualsiasi altro segmento di path (per esempio, `post/hello`, `post/2022-10-31`, ecc). Il `:postId` (poiche' inizia con i due punti iniziali `:`) verra' trattato come un parametro a cui verra' assegnato qualsiasi value che fa parte dell'URI in quel punto&mdash;quindi `post/hello` avrebbe `'hello'` come `postId`, e `post/2017-10-31` avrebbe `'2017-10-31'` come `postId`.

Puoi accedere ai values assegnati agli URL parameters usando l'hook **`useParams`** fornito da `react-router`. Questo hook restituisce un object le cui keys sono i nomi dei parametri e i cui values sono i values dei parametri:

```jsx
import { useParams } from 'react-router';

function BlogPost(props) {
    //accedi ai URL params come object
    //e' anche comune usare qui l'object destructuring
    const urlParams = useParams();

    return (
        {/* postId era il URL parameter dall'esempio sopra! */}
        <h1>Stai guardando il blog post {urlParams.postId}</h1>
    )
}
```

Nel component `BlogPost` sopra, il value `urlParams` sara' un object che contiene values diversi a seconda della route:

- Se l'elemento e' renderizzato da `<Route path="posts/:postId" element={<BlogPost />} />`, allora
    - visitare `posts/hello` fara' si' che `urlParams` sia l'object `{postId: "hello"}`
    - visitare `posts/2022-10-31` fara' si' che `urlParams` sia l'object: `{postId: "2022-10-13"}`
- Se l'elemento e' renderizzato da `<Route path="posts/:date/:title" element={<BlogPost />} />`, allora
    - visitare `posts/2022-10-31/Ciao` fara' si' che `urlParams` sia l'object `{date: "2022-10-31", title: "Ciao"}` (nota i values multipli per i parametri multipli!)

Se vuoi lavorare con i **query parameters** (per esempio, la parte `?key1=value1&key2=value2` dell'URL), puoi usare l'hook `useSearchParams()`. Questo funziona in modo simile all'hook `useState()`, tranne che il value verra' memorizzato nel query parameter dell'URL invece che nello state del Component. Nota che i query parameters dovrebbero essere usati solo per values come le search queries che _non corrispondono a una risorsa consistente_.


### Linking {-}
Anche se specificare elementi `<Route>` ti permettera' di mostrare "pagine" diverse a URL diversi, perche' una Single Page Application funzioni devi poter _navigare tra le routes_ senza causare il reload della pagina. Quindi non puoi semplicemente usare normali elementi `<a>` per linkare tra "pagine"&mdash;i browser interpretano il click su elementi `<a>` come un comando per inviare una nuova HTTP request, mentre tu vuoi solo cambiare l'URL e re-renderizzare l'App.

Invece, React Router fornisce un elemento **`<Link>`** che puoi usare per creare un hyperlink verso un'altra route dentro l'application. Questo component prende una prop **`to`** che usi per specificare la route a cui linka:

```jsx
<Link to="about">Clicca per visitare la pagina About</Link>
```

- Il component renderizzera' un elemento `<a>` con un handler `onClick` speciale che impedisce al browser di caricare una nuova pagina. Quindi puoi specificare qualsiasi contenuto che metteresti nell'`<a>` (come il testo del link) come child content del `<Link>`. Importante: un `<Link>` e' un _sostituto_ di un elemento `<a>`&mdash;non cercare di metterne uno dentro l'altro!

- Una property `to` che e' un path _relative_ (quindi senza `/` iniziale) verra' risolta in modo relativo alla sua parent route. Quindi puoi usare `..` per riferirti alla parent route come faresti con qualsiasi altro path relativo.

React Router fornisce anche un Component `<NavLink>`. Questo funziona esattamente come il component `<Link>`, tranne che se la route `to` matcha la _route corrente_, allora l'elemento avra' aggiunta la class CSS `active`. Questo e' usato per esempio per "highlightare" il link alla pagina in cui ti trovi nella sezione di navigazione, aiutando lo user a capire dove si trova nella pagina. E' anche possibile specificare una callback function se vuoi usare un nome custom per la class "active"; vedi la documentazione per un esempio (attenzione al [ternary operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Conditional_Operator)).


#### Redirecting {-}
Oltre agli elementi `<Link>` che permettono allo user di navigare cliccando un elemento, React Router fornisce anche funzionalita' per navigare _programmaticamente_ tra le routes.

Il tool principale per questo e' l'hook [**`useNavigate()`**](https://reactrouter.com/en/6.4.4/hooks/use-navigate). Questo hook, quando chiamato, fornira' una function (convenzionalmente chiamata `navigate`) che puo' essere chiamata per redirectare l'App&mdash;per cambiare l'URL senza ricaricare la pagina (e quindi causare il re-render delle Routes):

```jsx
import { useNavigate } from 'react-router';

//Un semplice form component
function Form(props){
    const navigate = useNavigate(); //accedi alla function navigate

    //event handler per il form
    const handleSubmit = function(event) {
        event.preventDefault();
        //fai qui il lavoro di form submission

        navigate("/home") //naviga alla route `/home`
    }

    return (
      <form onSubmit={handleSubmit}> ... </form>
    )
}
```

La function `navigate()` prende un argomento con lo stesso stile che useresti come prop `to` per un elemento `<Link>`.

- Dovresti usare la function `navigate()` solo quando azioni _non di navigazione_ (come le form submissions) devono causare redirect. Se lo user sta cliccando su un elemento per navigare, incapsula semplicemente quell'elemento in un `<Link>`&mdash;questo manterra' la tua pagina **accessibile**.

- Inoltre, chiama `navigate()` solo dall'interno di un event handler; non usarla nel body di una Component function&mdash;usa un elemento `<Navigate>`.

In alternativa, puoi causare il cambio di route renderizzando un elemento [**`Navigate`**](https://reactrouter.com/en/6.4.4/components/navigate). Questo elemento accetta una prop `to` proprio come un `<Link>`, e quando viene renderizzato reindirizzera' lo user come se il link fosse cliccato senza che lo user faccia nulla.

Per essere chiari: devi _renderizzare_ l'elemento `<Navigate>`&mdash;cioe' `return`arlo da un Component come DOM da renderizzare. Quindi invece di un component che restituisce, ad esempio, `<div>`, lo faresti restituire un `<Navigate>`. Quindi useresti questo elemento con conditional rendering, usando un `if` statement per determinare se vuoi restituire/mostrare contenuto DOM normale o invece restituire un `<Navigate>` per fare redirect.

- _DO NOT_ renderizzare un `<Navigate>` come child di contenuto mostrato (per esempio, dentro un `<div>`), perche' questo puo' causare problemi con il redirect che richiede piu' "DOM update cycles" per essere processato, interferendo con il processing della tua application. Invece, determina se dovresti fare redirect e in tal caso `return`a solo l'elemento `<Navigate>` (per esempio, con una condizione sentinella di "break early").

Gli elementi `<Navigate>` sono particolarmente utili quando crei "protected routes"&mdash;routes accessibili solo sotto certe condizioni (come se lo user e' loggato). Per farlo, fai in modo che l'`element` della Route includa un `if` statement per determinare se deve mostrare contenuto, o se invece deve mostrare `<Navigate>` e fare il redirect:

```jsx
function ProtectedPage(props) {
  //...determina se lo user e' loggato (ad es., via AJAX)

  if(!userIsLoggedIn) { //se non c'e' user, manda al sign in
    return <Navigate to="/signin">;
  }

  //altrimenti mostra il contenuto
  return (
    <div>contenuto protetto!</div>
  )
}
```

Una buona strategia e' combinare la logica sopra con una _nested route_, permettendoti di riusare la logica di autenticazione nella tua app:

```jsx
function RequireAuth(props) {
  //...determina se lo user e' loggato (ad es., via AJAX)

  if(!userIsLoggedIn) { //se non c'e' user, manda al sign in
    return <Navigate to="/signin">;
  }
  else { //altrimenti, mostra il contenuto della child route
    return <Outlet />
  }
}

function App(props) {
  return (
    <Routes>
      {/* protected routes */}
      <Route element={<RequireAuth />}>
        <Route path="profile" element={<ProfilePage />} />
        <Route path="secret" element={<SecretPage />} />
      </Route>
      {/* public routes */}
      <Route path="signin" element={<SignInPage />} />
    </Routes>
  )
}
```

La Route che renderizza `<RequireAuth>` non ha un `path` definito, quindi usa `""` di default (quindi non fornisce un segmento da considerare). Quindi se le sue child route sono matchate, quel component renderizzera' e o usera' `<Navigate>` per redirectare a una route pubblica, oppure mostrera' l'elemento della child route al posto dell'`<Outlet>`. Questa struttura ti permette di tenere organizzate le tue protected routes, mantenendo tutta la logica "user is logged in" in una singola location.


### React Router e Hosting {-}
Il client-side routing di React Router introduce alcune considerazioni aggiuntive quando vuoi deployare la tua app su un server non di sviluppo, come Github Pages (per esempio, cosa succede quando deployi un progetto Vite).

_Primo_, considera cosa succede quando digiti una route (per esempio, `https://domain.com/about` per accedere alla route `/about`) nella URL bar del browser per navigarci. Questo crea una HTTP Request per la risorsa all'URI con path `/about`. Quando quella request viene ricevuta dal web server, quel server eseguira' il _server-side routing_ e tentera' di accedere alla risorsa in quella location (per esempio, cerchera' una pagina `/about/index.html`). Ma non e' quello che vuoi che accada&mdash;poiche' non c'e' contenuto in quella risorsa (nessun `/about/index.html`), il server restituira' un errore [404](https://http.cat/404).

Invece, vuoi che il server prenda la request per la risorsa `/about` e _invece_ restituisca la tua pagina root `/index.html`, ma con il codice JavaScript appropriato che permettera' al _client-side routing_ di cambiare la URL bar del browser e mostrare il contenuto alla route `/about`. In effetti, vuoi che il server possa restituire la tua pagina root `index.html` indipendentemente da quale route sia specificata nella HTTP Request!

E' perfettamente possibile avere un web server che faccia questo (cioe', _non_ eseguire server-side routing e invece restituire sempre `/index.html` indipendentemente da quale risorsa e' richiesta); infatti, questo e' cio' che fa il development server di Create React App. Tuttavia GitHub Pages non ha questa funzionalita': se invii una HTTP request per una risorsa che non esiste (per esempio, `/about`), riceverai un errore 404. Ci sono alcuni modi per aggirare questo problema:

1. Puoi usare un `<HashRouter>` invece di un `<BrowserRouter>`. `<HashRouter>` usa la parte [fragment identifier](https://en.wikipedia.org/wiki/Fragment_identifier) dell'URI per registrare e tracciare quale route lo user sta visualizzando: la HTTP request viene quindi inviata a `https://domain.com/index.html#/about` per ottenere la route `/about`&mdash;e dato che `index.html` e' la risorsa di default, puo' essere abbreviato a `https://domain.com/#/about`, che e' _quasi_ altrettanto buono. In questo modo stai sempre richiedendo la risorsa appropriata (`/index.html`), ma puoi comunque eseguire client-side routing. Il compromesso e' che i tuoi URL avranno simboli `#` extra (il che rende anche piu' difficile usare la navigazione interna con il fragment), e andare a `domain.com/about` causera' _comunque_ un errore 404. E' consigliato **evitare** questo elemento se possibile.

2. Un altro approccio e' sostituire la pagina 404 del tuo server con qualcosa che va al tuo `index.html` (usando il _server-side routing_)&mdash;quindi invece di mostrare il 404 allo user, gli viene mostrata la tua `index.html` che sta per fare il client-side routing! [`spa-github-pages`](https://github.com/rafrex/spa-github-pages) fornisce un po' di boilerplate per farlo con GitHub Pages, ma e' un approccio "hacky" e quindi non e' consigliato.

3. L'approccio **migliore e corretto** e' usare un sistema di web hosting che supporti meglio il server-side routing necessario per le single-page applications. Per esempio, [Firebase Hosting](https://firebase.google.com/docs/hosting/) ti permette di specificare una [rewrite rule](https://firebase.google.com/docs/hosting/url-redirects-rewrites#section-rewrites) che fara' si' che il server restituisca il tuo `index.html` indipendentemente da quale route sia specificata nella HTTP Request. Create React App fornisce [istruzioni](https://create-react-app.dev/docs/deployment/#firebase) su come deployare su Firebase Hosting, includendo una semplice configurazione guidata che ti permette di configurare il tuo sito come single-page application.

<!-- _Secondo_, oltre al problema del server-side routing, dovrai fare lavoro extra per gestire gli elementi `<Redirect>` se l'URL della tua application e' in una _subresource_ del server (per esempio, si trova a `https://domain.com/app/index.html`). Mentre gli elementi `<Link>` instraderanno correttamente in questo caso (`<Link to='/home'>` andra' a `https://domain.com/app/home`), gli elementi `<Redirect>` _sovrascriveranno_ la parte path dell'URI: `<Redirect to='/home'>` ti portera' a `https://domain.com/home`, perdendo il fatto che la tua application e' nella risorsa `/app`.

Per fortuna, e' facile supportare questo comportamento e dire a React Router che tutti i path dovrebbero essere trattati in modo relativo a quella subresource (relativo al path `/app`). Lo fai passando la prop [**`basename`**](https://reacttraining.com/react-router/web/api/BrowserRouter/basename-string) al `<Router>`:

```jsx
<BrowserRouter basename={process.env.PUBLIC_URL+'/'}>
```

- Questo esempio specifica che l'URI "base" dovrebbe essere qualunque URI sia stato elencato nella key `"homepage"` del file `package.json` del progetto, come quello che specifichi quando [deployi Create React App su Github Pages](https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#github-pages). Vorrai usare esattamente quell'espressione (`process.env.PUBLIC_URL`), che e' una variable globale che si riferisce all'ambiente del processo node di bundling; la key `PUBLIC_URL` viene assegnata alla property `homepage` da Create React App. -->


## Risorse {-}
<div class="list-condensed">
- [Documentazione React Router](https://reactrouter.com/start/library/installation) - include tutorial ed esempi
- [React Router API](https://api.reactrouter.com/v7/) - lista completa di Components e hooks
</div>
