# Laboratorio: Webpack {#webpack}

Questo lab ha lo scopo di guidarti attraverso le basi del sistema di module bundling [**Webpack**](https://webpack.js.org/concepts/). Webpack e' il tool piu' comunemente usato nella comunita' React & Javascript per _transpilare_ e _bundlare_ components, ed e' cio' che viene usato sotto il cofano da [create-react-app](https://github.com/facebookincubator/create-react-app) (lo useremo la prossima settimana!). Anche se quel tool di scaffolding significa che non devi sapere come configurare Webpack, e' bene avere almeno una certa familiarita' con il concetto (e questo esercizio ti dara' ulteriore pratica nel lavorare con i moduli `npm`).

_Questo tutorial e' adattato da uno di [Tyler McGinnis](https://tylermcginnis.com/react-js-tutorial-1-5-utilizing-webpack-and-babel-to-build-a-react-js-app-5f804d729d3b#.3v5n4cd1z)._

## Che cos'e' Webpack?
Webpack e' un **build tool**. Cioe', e' un'applicazione (da command line) usata per prendere automaticamente il source code che scrivi e prepararlo per essere eseguito, sia per development che per deployment. Esistono numerosi build tool di questo tipo: [Gulp](http://gulpjs.com/) e' il principale concorrente di Webpack, e la maggior parte degli IDE (come jGrasp o IntelliJ) li fornisce. Tuttavia, Webpack e' preferito dagli sviluppatori React per quanto facilmente e velocemente transpilera' JSX.

Al suo core, Webpack e' un module loader: prende file sorgente come i **modules** JavaScript e li bundle in pochi file semplificati che possono far parte della tua pagina web. Prende la tua struttura di source code complicata (molti file) e la trasforma in una versione nuova e "semplificata" (pochi file).

## Getting Started

Ci sono due cose che devi fare per iniziare:

1. Prima, dobbiamo creare il file `package.json` per memorizzare informazioni sull'app che stai costruendo, incluse le dependencies che Webpack usera'. Puoi farlo con il seguente comando:

    ```bash
    cd path/to/project
    npm init
    ```

Ti verra' chiesto di fornire diverse informazioni sulla tua app. Fornisci i seguenti dettagli (**premi semplicemente `<enter>` per accettare i dettagli sugli altri prompt**)

- `name` dovrebbe essere "webpack-tutorial"
- `author` dovrebbe essere il tuo nome

Una volta finito, ti verra' chiesto di confermare le tue scelte (digita `yes`), e avrai un nuovo file `package.json` pronto all'uso!

> :bulb: Se vuoi solo un file `package.json` vuoto, usa `npm init -y` per saltare i prompt!


2. Installa localmente il programma `webpack`. Questo ti permettera' di eseguire il programma dalla command line e bundlare la tua app. Usare il flag `--save-dev` salva il modulo nelle tue `devDependencies`, che _*non*_ verranno bundlate nella versione bundle della tua app.

    ```
    npm install --save-dev webpack
    ```

## <code>webpack.config.js</code>
Anche se Webpack puo' essere usato per fare un semplice bundling dalla command line (vedi [il tutorial ufficiale](https://webpack.js.org/guides/getting-started//) per un esempio), e' piu' comune scrivere tutte le opzioni di bundling dentro un **file di configurazione**. Questo file e' semplicemente un file JavaScript che definisce una variable che rappresenta tutte le diverse opzioni che vuoi passare al programma `webpack`. Se chiami questo file **`webpack.config.js`**, Webpack leggera' la configurazione automaticamente. Quindi "usare Webpack" comporta davvero la creazione di questo file.

1. Crea un nuovo file chiamato **`webpack.config.js`** e aprilo nel tuo editor preferito (per esempio, VS Code).

2. Dentro questo file, aggiungi la seguente riga di codice:

    ```javascript
    module.exports = {}
    ```

    Questa e' la versione [CommonJS](http://requirejs.org/docs/commonjs.html) di `export default {}` in ES6&mdash;stai definendo un object (inizialmente vuoto) che verra' esportato e usato dal programma Webpack. **Il resto di questo tutorial comportera' l'aggiunta di properties a questo object**.

    - Nota che e' _possibile_ usare i comandi `import` ed `export` in stile ES6, ma devi chiamare il tuo file `webpack.config.babel.js` e dovrai avere alcune libraries Babel installate. Vedi [qui](http://stackoverflow.com/questions/31903692/how-to-use-es6-in-webpack-config) per una discussione. Per questo lab, resta sulla sintassi CommonJS.

Il lavoro base di Webpack e' prendere i tuoi source files, cambiarli in qualche modo, e produrre una nuova versione. Quindi ci sono tre cose che dovrai specificare:

1. Quali file trasformare (in particolare: quale file JavaScript fa partire il tuo programma)
2. Quali trasformazioni fare
3. Dove salvare i file trasformati

### <code>entry</code> e <code>output</code> {-}
Specifichiamo il primo pezzo (quali file trasformare) dando all'object esportato una property `entry`:

```javascript
module.exports = {
  //lista di entry points
  entry: [
    __dirname + '/src/index.js'
  ]
}
```

Questo indica quale file (relativo alla _cartella in cui ti trovi_) e' lo "start" o "entry point" del tuo programma&mdash;in un certo senso, quale file ha il "main" al suo interno. Nel nostro caso, `src/index.js` (il `__dirname` e' una costante Node che si riferisce alla directory di lavoro corrente). Nota che la property `entry` e' in realta' un _array_, dato che e' possibile supportare piu' entry points.

Salteremo per un momento il passo 2 e specificheremo anche dove salvare i file trasformati. Questo e' specificato come property `output` dell'object di config:

```javascript
module.exports = {
  entry: [
    __dirname + '/src/index.js'
  ],
  output: {
    filename: "bundle.js",
    path: __dirname + '/dist'
  },
}
```

La property `output` e' a sua volta un object con piu' dettagli sull'output (piuttosto che un array di possibili output). L'esempio sopra dice che dovremmo produrre l'output nella cartella `dist` (nella directory corrente), combinando il codice in un file chiamato `bundle.js`.

Dato che non abbiamo webpack installato globalmente (cosa che puoi fare se vuoi con `npm install -g webpack`), dovremo aggiungere qualcosa al nostro file `package.json`, per dire a `npm` cosa fare con i nostri file locali!

Aggiungendo al tuo file `package.json`, dovremo aggiornare la key `scripts`:

```json
...
"scripts": {
  "test": "echo \"Error: no test specified\" && exit 1",
  "build": "webpack"
},
...
```

Ora, se esegui `npm run build`, il project verra' buildato! Similmente a `npm install`, quando eseguiamo questo comando, diciamo a `npm` che, dentro questo project, vogliamo `run` lo script `build`, che chiamera' la versione locale di `webpack` per essere eseguita. Quando `webpack` gira, cerca il file `webpack.config.js`, e poi esegue usando quel file per buildare il tuo project!

Ecco approssimativamente l'output che dovresti vedere:

```
> webpack-demo@1.0.0 build /Users/joelross/Desktop/webpack-demo
> webpack

Hash: fc5c075a9cfa7ee938c0
Version: webpack 3.8.1
Time: 56ms
    Asset  Size  Chunks             Chunk Names
bundle.js  3 kB       0  [emitted]  main
   [0] multi ./src/index.js 28 bytes {0} [built]
   [1] ./src/index.js 390 bytes {0} [built]
```

Questo creera' un nuovo file `dist/bundle.js`. Se guardi questo file in VS Code, vedrai che contiene del codice extra che organizza i diversi **modules** in **functions** (per supportare lo scoping delle variables), una delle quali e' il contenuto del file `index.js`!


## Loaders
[Guarda tutto questo rosso!](https://kangax.github.io/compat-table/es6/) Questo e' il supporto che ES6 ha tra i modern browser di oggi. Cosa significa? Anche se le feature ES6 vengono adottate sempre di piu', non c'e' un supporto _*uniforme*_ completo. Quindi, dobbiamo fare un piccolo trucco chiamato _*transpiling*_ del nostro codice cosi' che tutti i browser sappiano cosa sta facendo il nostro Javascript.

Per fare questo, usiamo quelli che si chiamano **loaders**. Un loader e' fondamentalmente un plugin usato per eseguire una trasformazione particolare (per esempio, transpilare JSX o anche la sintassi ES6!). La forza di Webpack e' il suo set di loaders che gli permettono di gestire praticamente qualsiasi tipo di file e trasformazione. (E' ovviamente possibile scrivere i propri, ma questo e' ben oltre lo scopo di questo tutorial).

La property `module` e' usata per specificare la lista di `loaders`:

```javascript
module.exports = {
  entry: [
    __dirname + '/src/index.js'
  ],
  output: {
    filename: "bundle.js",
    path: __dirname + '/dist'
  },
  module: {
    loaders: [
      {
        test: /\.jsx?$/,
        loaders: ["babel-loader"],
      }
    ]
  },
}
```

La property `module` e' un object che contiene a sua volta una property `loaders`, che e' un _array_ di loaders da applicare. Ogni loader e' descritto come un object (vedi? Il nesting c'e' davvero!).

- La property `test` indica quali tipi di file vogliamo trasformare con il loader. Questo puo' sembrare spaventoso e confuso, ma e' perche' usa una [Regular Expression](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions) (simile a come splitti le parole nel JavaScript Challenge) per specificare l'_estensione del file_ che vogliamo considerare. Questa espressione specifica file che **terminano in** `.js` **o** `.jsx` (quest'ultima e' spesso usata per JSX React components). Come dare un senso a questa espressione e alla sua punteggiatura strana:

    - Le regular expressions sono come Strings, ma racchiuse da `/ /` invece che da `" "`
    - Il `.` in `.js` deve essere _escaped_, quindi ha un `\` davanti. Come `\n` per le newline.
    - La `x` in `.jsx` e' _optional_ (senza di essa abbiamo `.js`, che va bene), quindi e' scritta con un `?` dopo per indicare che puo' essere presente o no.
    - L'ultimo `$` indica la "fine della linea", quindi significa che parleremo solo di file che _terminano_ in `.js` (per esempio, `libray.js.css` non verrebbe trasformato).

- La property `loaders` e' una lista di quali loaders vogliamo applicare ai file i cui nomi matchano il "test". Nel nostro caso, usiamo [Babel](http://babeljs.io/docs/setup/#installation) per trasformare il nostro JSX, quindi useremo `"babel"` come loader.


### Babel Loader {-}
Loaders come Babel devono essere installati individualmente usando `npm` come se fossero programmi separati (dato che in effetti sono libraries separate!). Quindi dovremo installare il package `babel-loader` per poter applicare le trasformazioni di Babel:

```bash
npm install babel-loader --save-dev
```

- (L'argomento `--save-dev` qui e' come `--save` in quanto salva la dependency nel tuo file `package.json`. Tuttavia, `--save-dev` elenca la dependency come necessaria solo per il _development_, non per il _deployment_. Quindi se volessi caricare il tuo codice su un web server (come su [AWS](https://aws.amazon.com/)), questo farebbe sapere al server che non ha bisogno di installare Babel perche' hai gia' transpilato il codice in un build di produzione).

Ma siccome nulla e' mai semplice, il `babel-loader` richiede in realta' una library aggiuntiva (`babel-core`, che e' il programma Babel stesso) per fare il suo lavoro. Quindi dobbiamo installare anche:

```bash
npm install babel-core --save-dev
```

Babel e' in grado di eseguire tutti i tipi di trasformazioni, come compilare JSX e convertire la sintassi ES6 in versioni piu' vecchie compatibili con i browser. Babel e' molto modulare, quindi ogni trasformazione che vogliamo applicare puo' essere scaricata come library individuale chiamata [**preset**](https://babeljs.io/docs/plugins/).

```bash
npm install babel-preset-es2015 --save-dev
```

Questo installa `babel-preset-es2015` (la trasformazione per ES6).

Ovviamente, scaricare i preset non dice automaticamente a Babel di usarli. Per farlo, dobbiamo creare _un altro file_ che conterra' quali preset Babel dovrebbe usare. Questo file si chiama **`.babelrc`** ("rc" sta per "run commands"; nota il `.` iniziale che indica un file nascosto). Crea questo file **nella stessa directory di `webpack.config.js`**.

Il tuo file `.babelrc` contiene solo del JSON che indica quali preset usare (sono possibili anche altre opzioni):

```json
{
  "presets": ["es2015"]
}
```

In totale, hai specificato quali trasformazioni Babel applicare (in `.babelrc`), e hai detto al tuo file di config Webpack di usare Babel per modificare qualsiasi file JavaScript.

Quindi finalmente, dovresti essere in grado di usare `webpack` per buildare una versione funzionante del tuo programma React _la prossima settimana_! Apri il file `index.html` in un Browser per vedere la tua app.

Alcune cose da notare:

- Tutto il tuo codice e' dentro il file `bundle.js`.
- Ogni volta che cambi il tuo codice, dovrai "re-buildare" la tua application (eseguire di nuovo `webpack`). Esistono ulteriori plugin webpack che possono aiutare ad automatizzare questo, come quelli che aggiornano automaticamente la pagina quando i source file cambiano.

### Clean up :bath: {-}

Ora che abbiamo fatto il duro lavoro per far bundlare i nostri file da webpack, convertiamo davvero i nostri file alla sintassi ES6 corretta e usiamo gli import statements corretti, dato che solo Chrome supporta l'import nativo con [eccezioni speciali](http://caniuse.com/#feat=imports).

1. Assicurati di esportare le functions da `src/sorter.js`, `src/looper.js` e `src/printer.js`!
2. Ora che sono esportate, usa la sintassi ES6 in `src/index.js` per importare le functions
> Suggerimento: la 3a sintassi nella lista [qui](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import)
3. Elimina i tag `<script>` di `index.html` per i tuoi file.
4. Un'ultima cosa: in `src/sorter.js`, stiamo usando un package npm chiamato [`lodash`](https://lodash.com/) per ordinare l'array. Esegui `npm install --save lodash` (`--save` perche' vogliamo che il modulo sia usato nella nostra app finale) e poi importa `lodash` nel file `src/sorter.js`. Suggerimento: usa la seconda sintassi di import dalle docs MDN

Con un po' di fortuna, eseguire `npm run build` un'ultima volta dovrebbe darti un buon output, e infine, aprire `index.html` e guardare il console log dovrebbe mostrarti il tuo array di user ordinato!

### Ulteriore pratica con i Loader {-}
La pagina web non sembra ancora bella, perche' non c'e' styling (CSS) coinvolto. Per fare pratica con i webpack loaders, aggiungi un `import` per lo stylesheet `main.css` nel tuo `index.js`, e modifica `webpack.config.js` in modo che bundli quel file:

1. Aggiungi l'import nel tuo file `index.js`. Il file path dovrebbe essere _relativo_ al file `index.js`.

2. Installa i webpack loaders **`style-loader`** e **`css-loader`** (ricorda `--save-dev`). Insieme, questi loaders sono in grado di gestire i file CSS.

3. Aggiungi un altro elemento all'array `module.loaders` nel file `webpack.config.js` per specificare la trasformazione `style-loader`.

    - Il `test` dovrebbe essere una regular expression per file che terminano in **`.css`**
    - Il `loader` stesso dovrebbe essere `"style-loader!css-loader"`, che si riferisce al modulo "css loader" per il plugin style-loader.

4. Re-builda la tua application usando `webpack`. Se ricarichi la pagina, dovresti ora vedere che ha uno sfondo grigio!

Ci sono molte altre configurazioni e opzioni usate da Webpack. Per esempio, puoi usare il [webpack-dev-server](http://webpack.github.io/docs/webpack-dev-server.html) per far girare a webpack un server locale che rebundle automaticamente i moduli quando i file cambiano. Sei incoraggiato a dare un'occhiata a quell'esempio se hai tempo.

<small>Lab scritto in parte da Evan Frawley</small>
